In [1]:
import cv2
import numpy as np
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.io
import heapq
import xlsxwriter
from xlutils.copy import copy    
from xlrd import open_workbook
import os
import math
from scipy import ndimage

In [2]:
# Search all data with _highBW.mat and save to files
path = os.path.abspath("/media/peppermint/easystore/123/Patients")
print(path)
files = []
paths=[];
# Find file with _ute.ni 

for r, d, f in os.walk(path):
    d.sort()
    for file in f:
        if '.mat' in file:
            index=-3;
            name=[];
            find_=False;
            #print(r)
            while(not find_):
                if(file[index]=='.'):
                    find_= True;
                index=index-1;
                if(find_):
                    name.append(file[0:index+1]);
            files.append(name)
            paths.append(r)


/media/peppermint/easystore/123/Patients


In [16]:
excel_ro = open_workbook("/home/peppermint/Desktop/Full_scan.xls")
excel = copy(excel_ro)  # creates a writeable copy
# find the last line
sheet1 = excel.get_sheet(0)  # get a first sheet
tempt_sheet = excel_ro.sheet_by_index(0)
colx = 0
rowx = tempt_sheet.nrows;



for num_file in range(len(files)):
#for num_file in range(10):
    # load data
    try:   
        current_path = paths[num_file]+'/'+str(files[num_file][0])+'.mat';
        #print(current_path)
        mat = scipy.io.loadmat(current_path)
        bar2gas = mat['bar2gas']
        mask_reg = mat['mask_reg']


        total_mean=[];
        for ij in range(128):

            bar2gas_current = ndimage.rotate(bar2gas[ij,:,:],90);
            mask_current = ndimage.rotate(mask_reg[ij,:,:],90);

            if(sum(sum(mask_current))>=900):
                current_img=bar2gas_current ;

                output=cv2.connectedComponentsWithStats(mask_current,4)

                num_labels = output[0];
                labels_im = output[1];
                stats=output[2];
                centroid=output[3];

                if(num_labels<=2):
                    continue

                area=stats[:,4];
                # Delete the background label.
                area=area[1:]

                #Choose the label with largest and second largest except backgrounf
                index_label=np.array(heapq.nlargest(2, range(len(area)), key=area.__getitem__))+1;

                # Find which is left or right
                index_1 = index_label[0]
                index_2 = index_label[1]
                if (centroid[index_1,0]<centroid[index_2,0]):
                    left_label=index_1;
                    right_label=index_2;
                else:
                    left_label=index_2;
                    right_label=index_1;

                # Instant of Do morphology we create distance image 

                dist_transform = cv2.distanceTransform(mask_current,cv2.DIST_L2,3)
                [m,n] = current_img.shape
                sum_left_out=0;
                sum_right_out=0;
                sum_left_in=0;
                sum_right_in=0;

                num_left_out=0;
                num_right_out=0;
                num_left_in=0;
                num_right_in=0;

                for i in range(m):
                    for j in range(n):

                        if(labels_im[i,j]==left_label ):

                            if((dist_transform[i,j]>0 and dist_transform[i,j]<=3)):
                                sum_left_out = sum_left_out+ current_img[i,j];
                                num_left_out= num_left_out+1;
                            else: 
                                sum_left_in = sum_left_in+ current_img[i,j];
                                num_left_in= num_left_in+1;


                        elif (labels_im[i,j]==right_label):

                            if((dist_transform[i,j]>0 and dist_transform[i,j]<=3)):
                                sum_right_out = sum_right_out+ current_img[i,j];
                                num_right_out= num_right_out+1;
                            else:
                                sum_right_in = sum_right_in+ current_img[i,j];
                                num_right_in= num_right_in+1;


                mean=[];
                have_nan = False;

                if num_left_out!=0:
                    mean.append(sum_left_out/num_left_out);
                else:
                    mean.append(np.nan);
                    have_nan = True;

                if num_left_in!=0:
                    mean.append(sum_left_in/num_left_in);
                else:
                    mean.append(np.nan);
                    have_nan = True;

                if num_right_out!=0:
                    mean.append(sum_right_out/num_right_out);
                else:
                    mean.append(np.nan);
                    have_nan = True;    

                if num_right_in!=0:
                    mean.append(sum_right_in/num_right_in);
                else:
                    mean.append(np.nan);
                    have_nan = True;


                #if(not have_nan):
                #    total_mean.append(mean);
                total_mean.append(mean);

        total_mean=np.array(total_mean);
        total_mean=np.nanmean(total_mean,axis=0)
        #total_mean=np.mean(total_mean,axis=0)

        print(total_mean)
        name = files[num_file][0];
        colx = 0
        try:
            sheet1.write(rowx,colx, name)
            sheet1.write(rowx,colx+1, total_mean[0])
            sheet1.write(rowx,colx+2, total_mean[1])
            sheet1.write(rowx,colx+3, total_mean[2])
            sheet1.write(rowx,colx+4, total_mean[3])
            rowx = rowx+1;
        except:
            print('Something not right')
    except:
        print('Something not right')

excel.save("/home/peppermint/Desktop/Full_scan.xls")


[0.44843124 0.48651465 0.59772321 0.64035961]
[0.49034144 0.48482762 0.58537973 0.61098397]
[0.61570578 0.66219422 0.71046381 0.77967141]
[0.54511071 0.60269788 0.80925437 0.86894214]
[0.38803347 0.4118871  0.459798   0.5135132 ]
[0.53399953 0.5729237  0.64976843 0.67374766]
[0.66934607 0.62849702 0.65596723 0.64033829]
[0. 0. 0. 0.]
[1.16003811 1.26023361 1.31375625 1.33069169]
[1.29006337 1.39922766 1.30743948 1.41153393]
[0.62609169 0.66143093 0.63305358 0.67963262]
[0.68458839 0.75216802 0.71445337 0.7822859 ]
[0.30271268 0.44408645 0.2749762  0.41993407]
[0.27387331 0.49958119 0.3498613  0.52494759]
[0.12545753 0.19970707 0.13415518 0.18627708]
[0.1644806  0.20455302 0.17028162 0.18111429]
[0.09831396 0.14530689 0.09739562 0.17770246]
[0.16894038 0.23039399 0.16528383 0.21721317]
[0.15753475 0.23392608 0.12191709 0.17834256]
[0.26435476 0.26533165 0.22664124 0.24742646]
[0.50579486 0.52343451 0.51298108 0.52309432]
[0.39196065 0.67469131 0.35186457 0.54147226]
[0.79516357 0.865256

[1.35792685 1.39830882 1.26051443 1.29127592]
[1.11570559 1.34199732 1.49658856 1.61258551]
[1.07520782 1.17172952 1.31560841 1.37377762]
[0.92245958 0.95917057 1.09330589 1.12416609]
[0.91815162 0.94599092 1.09056376 1.09386181]
[0.73547045 0.82703861 0.79991439 0.86408705]
[0.57706722 0.69512355 0.59023184 0.65208561]
[0.60745041 0.66132552 0.74085251 0.83561783]
[0.59358    0.68302316 0.80372123 0.87834858]
[0.49686389 0.55718903 0.49474785 0.55691515]
[0.58497822 0.60922823 0.50328359 0.56184882]
[0.79262911 0.78696868 0.67805639 0.77860578]
[0.67074171 0.74564039 0.52230457 0.63237357]
[0.91867175 0.9012522  0.78257198 0.81822673]
[0.87477516 0.89994816 0.75982256 0.90417233]
[0.6862024  0.70184091 0.54463406 0.6452428 ]
[0.6862024  0.70184091 0.54463406 0.6452428 ]
[0.68476263 0.81027429 0.6351876  0.73574346]
[0.7149221  0.89394191 0.61528207 0.81790597]
[0.85050434 0.92385288 0.77451628 0.82831614]
[0.53013992 0.5595222  0.55283185 0.60221378]
[0.5921895  0.63368686 0.66553664 

In [30]:
excel_ro = open_workbook("/home/peppermint/Desktop/Full_scan3.xls")
excel = copy(excel_ro)  # creates a writeable copy
# find the last line
sheet1 = excel.get_sheet(0)  # get a first sheet
tempt_sheet = excel_ro.sheet_by_index(0)
colx = 0
rowx = tempt_sheet.nrows;

# number of split 
ns =3;


for num_file in range(len(files)):
#for num_file in range(1):
# load data
    try:   
        current_path = paths[num_file]+'/'+str(files[num_file][0])+'.mat';
        #print(current_path)
        mat = scipy.io.loadmat(current_path)
        bar2gas = mat['bar2gas']
        mask_reg = mat['mask_reg']


        total_mean=[];
        for ij in range(128):

            bar2gas_current = bar2gas[:,:,ij];
            mask_current = mask_reg[:,:,ij];

            if(sum(sum(mask_current))>=900):
                current_img=bar2gas_current ;

                output=cv2.connectedComponentsWithStats(mask_current,4)

                num_labels = output[0];
                labels_im = output[1];
                stats=output[2];
                centroid=output[3];

                if(num_labels<=2):
                    continue

                area=stats[:,4];
                # Delete the background label.
                area=area[1:]

                #Choose the label with largest and second largest except backgrounf
                index_label=np.array(heapq.nlargest(2, range(len(area)), key=area.__getitem__))+1;

                # Find which is left or right
                index_1 = index_label[0]
                index_2 = index_label[1]
                if (centroid[index_1,0]<centroid[index_2,0]):
                    left_label=index_1;
                    right_label=index_2;
                else:
                    left_label=index_2;
                    right_label=index_1;

                top_left= stats[left_label,1];
                height_left = stats[left_label,3];

                top_right= stats[right_label,1];
                height_right = stats[right_label,3];

                [m,n] = current_img.shape

                sum_left=[0] * ns;
                sum_right=[0] * ns;

                num_left=[0] * ns;
                num_right=[0] * ns;

                for i in range(m):
                    for j in range(n):

                        if(labels_im[i,j]==left_label ):

                            for nlf in range(ns):
                                if(i >= top_left +(height_left/3)*(nlf) and i <= top_left+ (height_left/3)*(nlf+1)):
                                    sum_left[nlf] = sum_left[nlf]+ current_img[i,j];
                                    num_left[nlf]= num_left[nlf]+1;


                        elif (labels_im[i,j]==right_label):
                            for nlf in range(ns):
                                if(i >= top_right +(height_right/3)*(nlf) and i <= top_right+ (height_right/3)*(nlf+1)):
                                    sum_right[nlf] = sum_right[nlf]+ current_img[i,j];
                                    num_right[nlf]= num_right[nlf]+1;


                mean=[];
                have_nan = False;

                for nlf in range(ns):
                    if(num_left[nlf]!=0):
                        mean.append(sum_left[nlf]/num_left[nlf])
                    else:
                        mean.append(np.nan);

                for nlf in range(ns):
                    if(num_right[nlf]!=0):
                        mean.append(sum_right[nlf]/num_right[nlf])
                    else:
                        mean.append(np.nan);


                #if(not have_nan):
                #    total_mean.append(mean);
                total_mean.append(mean);

        total_mean=np.array(total_mean);
        total_mean=np.nanmean(total_mean,axis=0)
        #total_mean=np.mean(total_mean,axis=0)
        print(total_mean)
        name = files[num_file][0];
        colx = 0
        try:
            sheet1.write(rowx,colx, name)
            for nlf in range(ns*2): 
                sheet1.write(rowx,colx+nlf+1, total_mean[nlf])

            rowx = rowx+1;
        except:
            print('Something not right')
    except:
        print('Something not right')

excel.save("/home/peppermint/Desktop/Full_scan3.xls")


[0.52730229 0.49499516 0.462896   0.58987524 0.57198061 0.62038752]
[0.51514327 0.49966577 0.44156603 0.58096284 0.58974875 0.6012695 ]
[0.65117844 0.65826546 0.58382503 0.7233868  0.73301099 0.6687189 ]
[0.65301713 0.6310186  0.61383403 0.80926083 0.79072054 0.81245041]
[0.44588158 0.40120094 0.42297262 0.56780721 0.46012755 0.47650531]
[0.53854298 0.51098282 0.56645278 0.5983913  0.60470829 0.69094613]
[0.75095638 0.59014719 0.60053638 0.71516039 0.67409901 0.73190329]
[0. 0. 0. 0. 0. 0.]
[1.08482935 1.3376538  1.13762905 1.20346542 1.44338665 1.36790317]
[1.22085427 1.45698569 1.10529791 1.2927964  1.55491471 1.30323889]
[0.60060686 0.66265781 0.64127224 0.54916679 0.65083065 0.65965361]
[0.65643738 0.75112724 0.70020677 0.62445155 0.73553658 0.76836637]
[0.3852226  0.39117183 0.30295299 0.39493161 0.38008833 0.278643  ]
[0.37500421 0.40126749 0.38163436 0.4512404  0.45717687 0.41310085]
[0.26541027 0.23880582 0.13329763 0.20468542 0.24580328 0.14896701]
[0.24163486 0.24278436 0.153

[0.80479319 0.79230215 0.73141875 0.84097276 0.80963306 0.67783462]
[0.51704753 0.54409679 0.59940226 0.46760635 0.54038986 0.58565888]
[0.49920631 0.51956416 0.61740671 0.39754082 0.44128725 0.49832025]
[0.51704753 0.54409679 0.59940226 0.46760635 0.54038986 0.58565888]
[0.49920631 0.51956416 0.61740671 0.39754082 0.44128725 0.49832025]
[0.30310848 0.57080301 0.54748189 0.40051464 0.55176212 0.55608659]
[0.80158526 0.75670316 0.69275843 0.76051989 0.6622253  0.45982508]
[0.74899213 0.75512699 0.56582322 0.71267171 0.62758214 0.43924653]
[0.92470022 0.93750012 0.7911276  0.93850854 0.81411822 0.53127117]
[1.00151974 0.98750665 0.87465045 1.09980901 0.98282883 0.67492648]
[0.93568919 0.90864155 0.80400092 0.92142184 0.90215576 0.8033439 ]
[0.86961716 0.84437445 0.75840156 0.85978526 0.84472113 0.72190038]
[0.94263963 0.87237091 0.75251086 0.86125325 0.81146317 0.73138376]
[1.02068266 0.95040817 0.82306487 0.95303762 0.87842019 0.77842578]
[0.99926088 0.90774832 0.79746468 0.85944599 0.8

[0.47334491 0.51470553 0.51499749 0.50325815 0.50223371 0.59158638]
[0.54673424 0.62072734 0.59571338 0.53830988 0.598613   0.47202618]
[0.09356967 0.10884482 0.02676017 0.18156409 0.12599047 0.04345064]
[0.81122514 0.87084009 0.85235367 0.59721323 0.84118143 0.85130674]
[0.55264925 0.6204255  0.50141816 0.54688507 0.58117768 0.5109848 ]
[0.52697696 0.58358922 0.50821656 0.55947103 0.60596811 0.49341209]
[0.82944108 0.73950023 0.75694687 0.79292107 0.78420498 0.75003709]
[0.22506133 0.44348995 0.4186223  0.21643186 0.42600916 0.43677485]
[0.15728243 0.11538671 0.0767888  0.184135   0.10305276 0.13270115]
[0.54461252 0.62298102 0.46936685 0.53994177 0.63004255 0.42107016]
[0.61529641 0.63986987 0.60787301 0.66412618 0.70806705 0.68475668]
[0.5741285  0.46333526 0.34153003 0.68186728 0.51989191 0.35108144]
[0.64907377 0.69565094 0.71384992 0.61523939 0.70253498 0.75562507]
[1.00207261 1.00004173 1.04217099 1.02952396 1.19282273 1.11206205]
[0.93737309 0.95329048 0.9171557  0.93711031 0.9

In [9]:
excel_ro = open_workbook("/home/peppermint/Desktop/NotAll_scan_3split_all_type.xls")
excel = copy(excel_ro)  # creates a writeable copy
# find the last line
sheet1 = excel.get_sheet(0)  # get a first sheet
tempt_sheet = excel_ro.sheet_by_index(0)
colx = 0
rowx = tempt_sheet.nrows;

# number of split 
ns =3;


#for num_file in range(len(files)):
for num_file in range(185):
#for num_file in range(1):
# load data
    try:   
        current_path = paths[num_file]+'/'+str(files[num_file][0])+'.mat';
        #print(current_path)
        mat = scipy.io.loadmat(current_path)
        
        type_of_data=['bar2gas','bar2gas_binning', 'rbc2gas','rbc2gas_binning','gas_highreso_cor','ven_binning'];
        
        number_types=len(type_of_data);
        
        mask_reg = mat['mask_reg']
        
        [rx,ry,rz]= np.array(mask_reg).shape;
        
        data_images=np.zeros([rx,ry,rz,number_types]);
        
        for num,wtype in enumerate(type_of_data): 
            data_images[:,:,:,num]= mat[wtype];
        

        total_mean=[];
        for ij in range(128):
            
            mask_current = mask_reg[:,:,ij];
   

            if(sum(sum(mask_current))>=900):
                

                output=cv2.connectedComponentsWithStats(mask_current,4)

                num_labels = output[0];
                labels_im = output[1];
                stats=output[2];
                centroid=output[3];

                if(num_labels<=2):
                    continue

                area=stats[:,4];
                # Delete the background label.
                area=area[1:]

                #Choose the label with largest and second largest except backgrounf
                index_label=np.array(heapq.nlargest(2, range(len(area)), key=area.__getitem__))+1;

                # Find which is left or right
                index_1 = index_label[0]
                index_2 = index_label[1]
                if (centroid[index_1,0]<centroid[index_2,0]):
                    left_label=index_1;
                    right_label=index_2;
                else:
                    left_label=index_2;
                    right_label=index_1;

                top_left= stats[left_label,1];
                height_left = stats[left_label,3];

                top_right= stats[right_label,1];
                height_right = stats[right_label,3];

                [m,n] = mask_current.shape

                sum_all=[0] * ns * 2 * number_types;

                num_all=[0] * ns * 2 * number_types;


                for i in range(m):
                    for j in range(n):

                        if(labels_im[i,j]==left_label ):
     
                            for nlf in range(ns):
                                if(i >= top_left +(height_left/3)*(nlf) and i <= top_left+ (height_left/3)*(nlf+1)):
                                    
                                    for num in range(number_types):
                                        sum_all[nlf+6*num] = sum_all[nlf+6*num]+ data_images[i,j,ij,num];
                                        num_all[nlf+6*num]= num_all[nlf+6*num]+1;


                        elif (labels_im[i,j]==right_label):
                            for nlf in range(ns):
                                if(i >= top_right +(height_right/3)*(nlf) and i <= top_right+ (height_right/3)*(nlf+1)):
                                    for num in range(number_types):
                                        sum_all[nlf+3+6*num] = sum_all[nlf+3+6*num]+ data_images[i,j,ij,num];
                                        num_all[nlf+3+6*num]= num_all[nlf+3+6*num]+1;


                mean=[];
                have_nan = False;
                for nlf in range(ns * 2 * number_types):
                    if(num_all[nlf]!=0):
                        mean.append(sum_all[nlf]/num_all[nlf])
                    else:
                        mean.append(np.nan);


                #if(not have_nan):
                #    total_mean.append(mean);
                total_mean.append(mean);

        total_mean=np.array(total_mean);
        total_mean=np.nanmean(total_mean,axis=0)
        #total_mean=np.mean(total_mean,axis=0)
        print(total_mean)
        name = files[num_file][0];
        colx = 0
        try:
            sheet1.write(rowx,colx, name)
            for nlf in range(ns * 2 * number_types): 
                sheet1.write(rowx,colx+nlf+1, total_mean[nlf])

            rowx = rowx+1;
        except:
            print('Something not right')
    except:
        print('Something not right')

excel.save("/home/peppermint/Desktop/NotAll_scan_3split_all_type.xls")


[5.27302293e-01 4.94995164e-01 4.62896001e-01 5.89875238e-01
 5.71980611e-01 6.20387517e-01 3.98520699e+00 3.84765907e+00
 3.68353272e+00 4.26175237e+00 4.19770820e+00 4.38850967e+00
 4.13261712e-01 4.08141397e-01 2.50464932e-01 3.81981542e-01
 3.47324557e-01 1.69871587e-01 4.52426592e+00 4.53502074e+00
 3.66629216e+00 4.40081574e+00 4.20690388e+00 3.22955487e+00
 2.21319930e-10 2.34446651e-10 2.37517839e-10 2.35409317e-10
 2.39152015e-10 2.41373086e-10 4.32348072e+00 4.49455574e+00
 4.57432773e+00 4.53320020e+00 4.59104241e+00 4.63235467e+00]


In [14]:
excel_ro = open_workbook("/home/peppermint/Desktop/NotAll_scan_2outin_all_type.xls")
excel = copy(excel_ro)  # creates a writeable copy
# find the last line
sheet1 = excel.get_sheet(0)  # get a first sheet
tempt_sheet = excel_ro.sheet_by_index(0)
colx = 0
rowx = tempt_sheet.nrows;

# number of split 
ns =2;


#for num_file in range(len(files)):
for num_file in range(185):
#for num_file in range(1):
# load data
    try:   
        current_path = paths[num_file]+'/'+str(files[num_file][0])+'.mat';
        #print(current_path)
        mat = scipy.io.loadmat(current_path)

        type_of_data=['bar2gas','bar2gas_binning', 'rbc2gas','rbc2gas_binning','gas_highreso_cor','ven_binning'];

        number_types=len(type_of_data);

        mask_reg = mat['mask_reg']

        [rx,ry,rz]= np.array(mask_reg).shape;

        data_images=np.zeros([rx,ry,rz,number_types]);

        for num,wtype in enumerate(type_of_data): 
            data_images[:,:,:,num]= mat[wtype];


        total_mean=[];
        for ij in range(128):

            mask_current = ndimage.rotate(mask_reg[ij,:,:],90);
            [rx,ry]= np.array(mask_current).shape;

            data_images_current=np.zeros([rx,ry,number_types]);

            for num in range(number_types):
                data_images_current[:,:,num]=ndimage.rotate(data_images[ij,:,:,num],90);


            if(sum(sum(mask_current))>=900):


                output=cv2.connectedComponentsWithStats(mask_current,4)

                num_labels = output[0];
                labels_im = output[1];
                stats=output[2];
                centroid=output[3];

                if(num_labels<=2):
                    continue

                area=stats[:,4];
                # Delete the background label.
                area=area[1:]

                #Choose the label with largest and second largest except backgrounf
                index_label=np.array(heapq.nlargest(2, range(len(area)), key=area.__getitem__))+1;

                # Find which is left or right
                index_1 = index_label[0]
                index_2 = index_label[1]
                if (centroid[index_1,0]<centroid[index_2,0]):
                    left_label=index_1;
                    right_label=index_2;
                else:
                    left_label=index_2;
                    right_label=index_1;

                top_left= stats[left_label,1];
                height_left = stats[left_label,3];

                top_right= stats[right_label,1];
                height_right = stats[right_label,3];

                [m,n] = mask_current.shape

                dist_transform = cv2.distanceTransform(mask_current,cv2.DIST_L2,3)

                sum_all=[0] * ns * 2 * number_types;

                num_all=[0] * ns * 2 * number_types;


                for i in range(m):
                    for j in range(n):

                        if(labels_im[i,j]==left_label ):


                                if((dist_transform[i,j]>0 and dist_transform[i,j]<=3)):
                                    nlf = 0;
                                else:
                                    nlf = 1; 


                                for num in range(number_types):
                                    sum_all[nlf+4*num] = sum_all[nlf+4*num]+ data_images_current[i,j,num];
                                    num_all[nlf+4*num]= num_all[nlf+4*num]+1;


                        elif (labels_im[i,j]==right_label):

                                if((dist_transform[i,j]>0 and dist_transform[i,j]<=3)):
                                    nlf = 0;
                                else:
                                    nlf = 1; 


                                for num in range(number_types):
                                    sum_all[nlf+2+4*num] = sum_all[nlf+2+4*num]+ data_images_current[i,j,num];
                                    num_all[nlf+2+4*num]= num_all[nlf+2+4*num]+1;


                mean=[];
                have_nan = False;
                for nlf in range(ns * 2 * number_types):
                    if(num_all[nlf]!=0):
                        mean.append(sum_all[nlf]/num_all[nlf])
                    else:
                        mean.append(np.nan);


                #if(not have_nan):
                #    total_mean.append(mean);
                total_mean.append(mean);

        total_mean=np.array(total_mean);
        total_mean=np.nanmean(total_mean,axis=0)
        #total_mean=np.mean(total_mean,axis=0)
        print(total_mean)
        name = files[num_file][0];
        colx = 0
        try:
            sheet1.write(rowx,colx, name)
            for nlf in range(ns * 2 * number_types): 
                sheet1.write(rowx,colx+nlf+1, total_mean[nlf])

            rowx = rowx+1;
        except:
            print('Something not right')
    except:
        print('Something not right')

excel.save("/home/peppermint/Desktop/NotAll_scan_2outin_all_type.xls")


[4.48431237e-01 4.86514654e-01 5.97723210e-01 6.40359612e-01
 3.57457426e+00 3.80495383e+00 4.28520416e+00 4.52453584e+00
 2.68704545e-01 2.93503071e-01 2.62502692e-01 2.50674661e-01
 3.66262260e+00 3.91316701e+00 3.72794455e+00 3.71129427e+00
 2.03024621e-10 2.51929370e-10 2.21247952e-10 2.69618093e-10
 4.08316289e+00 4.80295924e+00 4.32396843e+00 5.09748653e+00]


In [21]:
excel_ro = open_workbook("/home/peppermint/Desktop/NotAll_scan_2outin_3cut_all_type.xls")
excel = copy(excel_ro)  # creates a writeable copy
# find the last line
sheet1 = excel.get_sheet(0)  # get a first sheet
tempt_sheet = excel_ro.sheet_by_index(0)
colx = 0
rowx = tempt_sheet.nrows;

# number of split 
ns = 2*3;
number_cut=3;

#for num_file in range(len(files)):
for num_file in range(185):
#for num_file in range(1):
# load data
    try:   
        current_path = paths[num_file]+'/'+str(files[num_file][0])+'.mat';
        #print(current_path)
        mat = scipy.io.loadmat(current_path)

        type_of_data=['bar2gas','bar2gas_binning', 'rbc2gas','rbc2gas_binning','gas_highreso_cor','ven_binning'];

        number_types=len(type_of_data);

        mask_reg = mat['mask_reg']

        [rx,ry,rz]= np.array(mask_reg).shape;

        data_images=np.zeros([rx,ry,rz,number_types]);

        for num,wtype in enumerate(type_of_data): 
            data_images[:,:,:,num]= mat[wtype];


        total_mean=[];
        for ij in range(128):

            mask_current = ndimage.rotate(mask_reg[ij,:,:],90);
            [rx,ry]= np.array(mask_current).shape;

            data_images_current=np.zeros([rx,ry,number_types]);

            for num in range(number_types):
                data_images_current[:,:,num]=ndimage.rotate(data_images[ij,:,:,num],90);


            if(sum(sum(mask_current))>=900):


                output=cv2.connectedComponentsWithStats(mask_current,4)

                num_labels = output[0];
                labels_im = output[1];
                stats=output[2];
                centroid=output[3];

                if(num_labels<=2):
                    continue

                area=stats[:,4];
                # Delete the background label.
                area=area[1:]

                #Choose the label with largest and second largest except backgrounf
                index_label=np.array(heapq.nlargest(2, range(len(area)), key=area.__getitem__))+1;

                # Find which is left or right
                index_1 = index_label[0]
                index_2 = index_label[1]
                if (centroid[index_1,0]<centroid[index_2,0]):
                    left_label=index_1;
                    right_label=index_2;
                else:
                    left_label=index_2;
                    right_label=index_1;

                top_left= stats[left_label,1];
                height_left = stats[left_label,3];

                top_right= stats[right_label,1];
                height_right = stats[right_label,3];

                [m,n] = mask_current.shape

                dist_transform = cv2.distanceTransform(mask_current,cv2.DIST_L2,3)

                sum_all=[0] * ns * 2 * number_types;

                num_all=[0] * ns * 2 * number_types;


                for i in range(m):
                    for j in range(n):

                        if(labels_im[i,j]==left_label ):


                                if((dist_transform[i,j]>0 and dist_transform[i,j]<=3)):
                                    nlf = 0;
                                else:
                                    nlf = 1; 
                                for ncut in range(number_cut):
                                    if(i >= top_left +(height_left/3)*(ncut) and i <= top_left+ (height_left/3)*(ncut+1)):
                                        nlf_c = nlf + 2*ncut;
                                        for num in range(number_types):
                                            sum_all[nlf_c+12*num] = sum_all[nlf_c+12*num]+ data_images_current[i,j,num];
                                            num_all[nlf_c+12*num]= num_all[nlf_c+12*num]+1;


                        elif (labels_im[i,j]==right_label):

                                if((dist_transform[i,j]>0 and dist_transform[i,j]<=3)):
                                    nlf = 0;
                                else:
                                    nlf = 1; 

                                for ncut in range(number_cut):
                                    if(i >= top_left +(height_left/3)*(ncut) and i <= top_left+ (height_left/3)*(ncut+1)):
                                        nlf_c = nlf + 2*ncut;
                                        for num in range(number_types):
                                            sum_all[nlf_c+6+12*num] = sum_all[nlf_c+6+12*num]+ data_images_current[i,j,num];
                                            num_all[nlf_c+6+12*num]= num_all[nlf_c+6+12*num]+1;



                mean=[];
                have_nan = False;
                for nlf in range(ns * 2 * number_types):
                    if(num_all[nlf]!=0):
                        mean.append(sum_all[nlf]/num_all[nlf])
                    else:
                        mean.append(np.nan);


                #if(not have_nan):
                #    total_mean.append(mean);
                total_mean.append(mean);

        total_mean=np.array(total_mean);
        total_mean=np.nanmean(total_mean,axis=0)
        #total_mean=np.mean(total_mean,axis=0)
        print(total_mean)
        name = files[num_file][0];
        colx = 0
        try:
            sheet1.write(rowx,colx, name)
            for nlf in range(ns * 2 * number_types): 
                sheet1.write(rowx,colx+nlf+1, total_mean[nlf])

            rowx = rowx+1;
        except:
            print('Something not right')
    except:
        print('Something not right')

excel.save("/home/peppermint/Desktop/NotAll_scan_2outin_3cut_all_type.xls")

[5.48877919e-01 5.54475542e-01 4.18639854e-01 4.61321102e-01
 3.78495549e-01 4.28931721e-01 6.71149692e-01 6.90895145e-01
 6.04045853e-01 6.15294449e-01 5.00875345e-01 5.31284894e-01
 4.05432963e+00 4.11382953e+00 3.44488165e+00 3.70651651e+00
 3.23393516e+00 3.54197030e+00 4.62835855e+00 4.79994259e+00
 4.30080927e+00 4.35222369e+00 3.83743067e+00 3.99106111e+00
 3.46646956e-01 3.52451755e-01 2.98741800e-01 3.13084423e-01
 1.79869766e-01 1.99065410e-01 2.93116100e-01 2.67170852e-01
 2.70044789e-01 2.63245796e-01 1.93589973e-01 1.59950443e-01
 4.16870225e+00 4.23606913e+00 3.82136438e+00 4.02095818e+00
 3.11745149e+00 3.39768357e+00 3.92516621e+00 3.81118749e+00
 3.79028803e+00 3.76895336e+00 3.29531221e+00 3.13503402e+00
 2.15301248e-10 2.53674663e-10 1.93299500e-10 2.53956424e-10
 2.01045613e-10 2.54234594e-10 2.20215153e-10 2.69433295e-10
 2.25547978e-10 2.63283474e-10 2.23384974e-10 2.85019439e-10
 4.19492530e+00 4.79604614e+00 3.96670051e+00 4.86040124e+00
 4.11296987e+00 4.895825

In [ ]:
# Just copy above 3 code cause I am to lazy

In [3]:
excel_ro = open_workbook("/home/peppermint/Desktop/NotAll_scan_3split_all_type.xls")
excel = copy(excel_ro)  # creates a writeable copy
# find the last line
sheet1 = excel.get_sheet(0)  # get a first sheet
tempt_sheet = excel_ro.sheet_by_index(0)
colx = 0
rowx = tempt_sheet.nrows;

# number of split 
ns =3;


#for num_file in range(len(files)):
for num_file in range(210):
#for num_file in range(1):
# load data
    try:   
        current_path = paths[num_file]+'/'+str(files[num_file][0])+'.mat';
        #print(current_path)
        mat = scipy.io.loadmat(current_path)
        
        type_of_data=['bar2gas','bar2gas_binning', 'rbc2gas','rbc2gas_binning','gas_highreso_cor','ven_binning'];
        
        number_types=len(type_of_data);
        
        mask_reg = mat['mask_reg']
        
        [rx,ry,rz]= np.array(mask_reg).shape;
        
        data_images=np.zeros([rx,ry,rz,number_types]);
        
        for num,wtype in enumerate(type_of_data): 
            data_images[:,:,:,num]= mat[wtype];
        

        total_mean=[];
        for ij in range(128):
            
            mask_current = mask_reg[:,:,ij];
   

            if(sum(sum(mask_current))>=900):
                

                output=cv2.connectedComponentsWithStats(mask_current,4)

                num_labels = output[0];
                labels_im = output[1];
                stats=output[2];
                centroid=output[3];

                if(num_labels<=2):
                    continue

                area=stats[:,4];
                # Delete the background label.
                area=area[1:]

                #Choose the label with largest and second largest except backgrounf
                index_label=np.array(heapq.nlargest(2, range(len(area)), key=area.__getitem__))+1;

                # Find which is left or right
                index_1 = index_label[0]
                index_2 = index_label[1]
                if (centroid[index_1,0]<centroid[index_2,0]):
                    left_label=index_1;
                    right_label=index_2;
                else:
                    left_label=index_2;
                    right_label=index_1;

                top_left= stats[left_label,1];
                height_left = stats[left_label,3];

                top_right= stats[right_label,1];
                height_right = stats[right_label,3];

                [m,n] = mask_current.shape

                sum_all=[0] * ns * 2 * number_types;

                num_all=[0] * ns * 2 * number_types;


                for i in range(m):
                    for j in range(n):

                        if(labels_im[i,j]==left_label ):
     
                            for nlf in range(ns):
                                if(i >= top_left +(height_left/3)*(nlf) and i <= top_left+ (height_left/3)*(nlf+1)):
                                    
                                    for num in range(number_types):
                                        sum_all[nlf+6*num] = sum_all[nlf+6*num]+ data_images[i,j,ij,num];
                                        num_all[nlf+6*num]= num_all[nlf+6*num]+1;


                        elif (labels_im[i,j]==right_label):
                            for nlf in range(ns):
                                if(i >= top_right +(height_right/3)*(nlf) and i <= top_right+ (height_right/3)*(nlf+1)):
                                    for num in range(number_types):
                                        sum_all[nlf+3+6*num] = sum_all[nlf+3+6*num]+ data_images[i,j,ij,num];
                                        num_all[nlf+3+6*num]= num_all[nlf+3+6*num]+1;


                mean=[];
                have_nan = False;
                for nlf in range(ns * 2 * number_types):
                    if(num_all[nlf]!=0):
                        mean.append(sum_all[nlf]/num_all[nlf])
                    else:
                        mean.append(np.nan);


                #if(not have_nan):
                #    total_mean.append(mean);
                total_mean.append(mean);

        total_mean=np.array(total_mean);
        total_mean=np.nanmean(total_mean,axis=0)
        #total_mean=np.mean(total_mean,axis=0)
        print(total_mean)
        name = files[num_file][0];
        colx = 0
        try:
            sheet1.write(rowx,colx, name)
            for nlf in range(ns * 2 * number_types): 
                sheet1.write(rowx,colx+nlf+1, total_mean[nlf])

            rowx = rowx+1;
        except:
            print('Something not right')
    except:
        print('Something not right')

excel.save("/home/peppermint/Desktop/NotAll_scan_3split_all_type.xls")


# Second run



excel_ro = open_workbook("/home/peppermint/Desktop/NotAll_scan_2outin_all_type.xls")
excel = copy(excel_ro)  # creates a writeable copy
# find the last line
sheet1 = excel.get_sheet(0)  # get a first sheet
tempt_sheet = excel_ro.sheet_by_index(0)
colx = 0
rowx = tempt_sheet.nrows;

# number of split 
ns =2;


#for num_file in range(len(files)):
for num_file in range(210):
#for num_file in range(1):
# load data
    try:   
        current_path = paths[num_file]+'/'+str(files[num_file][0])+'.mat';
        #print(current_path)
        mat = scipy.io.loadmat(current_path)

        type_of_data=['bar2gas','bar2gas_binning', 'rbc2gas','rbc2gas_binning','gas_highreso_cor','ven_binning'];

        number_types=len(type_of_data);

        mask_reg = mat['mask_reg']

        [rx,ry,rz]= np.array(mask_reg).shape;

        data_images=np.zeros([rx,ry,rz,number_types]);

        for num,wtype in enumerate(type_of_data): 
            data_images[:,:,:,num]= mat[wtype];


        total_mean=[];
        for ij in range(128):

            mask_current = ndimage.rotate(mask_reg[ij,:,:],90);
            [rx,ry]= np.array(mask_current).shape;

            data_images_current=np.zeros([rx,ry,number_types]);

            for num in range(number_types):
                data_images_current[:,:,num]=ndimage.rotate(data_images[ij,:,:,num],90);


            if(sum(sum(mask_current))>=900):


                output=cv2.connectedComponentsWithStats(mask_current,4)

                num_labels = output[0];
                labels_im = output[1];
                stats=output[2];
                centroid=output[3];

                if(num_labels<=2):
                    continue

                area=stats[:,4];
                # Delete the background label.
                area=area[1:]

                #Choose the label with largest and second largest except backgrounf
                index_label=np.array(heapq.nlargest(2, range(len(area)), key=area.__getitem__))+1;

                # Find which is left or right
                index_1 = index_label[0]
                index_2 = index_label[1]
                if (centroid[index_1,0]<centroid[index_2,0]):
                    left_label=index_1;
                    right_label=index_2;
                else:
                    left_label=index_2;
                    right_label=index_1;

                top_left= stats[left_label,1];
                height_left = stats[left_label,3];

                top_right= stats[right_label,1];
                height_right = stats[right_label,3];

                [m,n] = mask_current.shape

                dist_transform = cv2.distanceTransform(mask_current,cv2.DIST_L2,3)

                sum_all=[0] * ns * 2 * number_types;

                num_all=[0] * ns * 2 * number_types;


                for i in range(m):
                    for j in range(n):

                        if(labels_im[i,j]==left_label ):


                                if((dist_transform[i,j]>0 and dist_transform[i,j]<=3)):
                                    nlf = 0;
                                else:
                                    nlf = 1; 


                                for num in range(number_types):
                                    sum_all[nlf+4*num] = sum_all[nlf+4*num]+ data_images_current[i,j,num];
                                    num_all[nlf+4*num]= num_all[nlf+4*num]+1;


                        elif (labels_im[i,j]==right_label):

                                if((dist_transform[i,j]>0 and dist_transform[i,j]<=3)):
                                    nlf = 0;
                                else:
                                    nlf = 1; 


                                for num in range(number_types):
                                    sum_all[nlf+2+4*num] = sum_all[nlf+2+4*num]+ data_images_current[i,j,num];
                                    num_all[nlf+2+4*num]= num_all[nlf+2+4*num]+1;


                mean=[];
                have_nan = False;
                for nlf in range(ns * 2 * number_types):
                    if(num_all[nlf]!=0):
                        mean.append(sum_all[nlf]/num_all[nlf])
                    else:
                        mean.append(np.nan);


                #if(not have_nan):
                #    total_mean.append(mean);
                total_mean.append(mean);

        total_mean=np.array(total_mean);
        total_mean=np.nanmean(total_mean,axis=0)
        #total_mean=np.mean(total_mean,axis=0)
        print(total_mean)
        name = files[num_file][0];
        colx = 0
        try:
            sheet1.write(rowx,colx, name)
            for nlf in range(ns * 2 * number_types): 
                sheet1.write(rowx,colx+nlf+1, total_mean[nlf])

            rowx = rowx+1;
        except:
            print('Something not right')
    except:
        print('Something not right')

excel.save("/home/peppermint/Desktop/NotAll_scan_2outin_all_type.xls")


# Third run 


excel_ro = open_workbook("/home/peppermint/Desktop/NotAll_scan_2outin_3cut_all_type.xls")
excel = copy(excel_ro)  # creates a writeable copy
# find the last line
sheet1 = excel.get_sheet(0)  # get a first sheet
tempt_sheet = excel_ro.sheet_by_index(0)
colx = 0
rowx = tempt_sheet.nrows;

# number of split 
ns = 2*3;
number_cut=3;

#for num_file in range(len(files)):
for num_file in range(210):
#for num_file in range(1):
# load data
    try:   
        current_path = paths[num_file]+'/'+str(files[num_file][0])+'.mat';
        #print(current_path)
        mat = scipy.io.loadmat(current_path)

        type_of_data=['bar2gas','bar2gas_binning', 'rbc2gas','rbc2gas_binning','gas_highreso_cor','ven_binning'];

        number_types=len(type_of_data);

        mask_reg = mat['mask_reg']

        [rx,ry,rz]= np.array(mask_reg).shape;

        data_images=np.zeros([rx,ry,rz,number_types]);

        for num,wtype in enumerate(type_of_data): 
            data_images[:,:,:,num]= mat[wtype];


        total_mean=[];
        for ij in range(128):

            mask_current = ndimage.rotate(mask_reg[ij,:,:],90);
            [rx,ry]= np.array(mask_current).shape;

            data_images_current=np.zeros([rx,ry,number_types]);

            for num in range(number_types):
                data_images_current[:,:,num]=ndimage.rotate(data_images[ij,:,:,num],90);


            if(sum(sum(mask_current))>=900):


                output=cv2.connectedComponentsWithStats(mask_current,4)

                num_labels = output[0];
                labels_im = output[1];
                stats=output[2];
                centroid=output[3];

                if(num_labels<=2):
                    continue

                area=stats[:,4];
                # Delete the background label.
                area=area[1:]

                #Choose the label with largest and second largest except backgrounf
                index_label=np.array(heapq.nlargest(2, range(len(area)), key=area.__getitem__))+1;

                # Find which is left or right
                index_1 = index_label[0]
                index_2 = index_label[1]
                if (centroid[index_1,0]<centroid[index_2,0]):
                    left_label=index_1;
                    right_label=index_2;
                else:
                    left_label=index_2;
                    right_label=index_1;

                top_left= stats[left_label,1];
                height_left = stats[left_label,3];

                top_right= stats[right_label,1];
                height_right = stats[right_label,3];

                [m,n] = mask_current.shape

                dist_transform = cv2.distanceTransform(mask_current,cv2.DIST_L2,3)

                sum_all=[0] * ns * 2 * number_types;

                num_all=[0] * ns * 2 * number_types;


                for i in range(m):
                    for j in range(n):

                        if(labels_im[i,j]==left_label ):


                                if((dist_transform[i,j]>0 and dist_transform[i,j]<=3)):
                                    nlf = 0;
                                else:
                                    nlf = 1; 
                                for ncut in range(number_cut):
                                    if(i >= top_left +(height_left/3)*(ncut) and i <= top_left+ (height_left/3)*(ncut+1)):
                                        nlf_c = nlf + 2*ncut;
                                        for num in range(number_types):
                                            sum_all[nlf_c+12*num] = sum_all[nlf_c+12*num]+ data_images_current[i,j,num];
                                            num_all[nlf_c+12*num]= num_all[nlf_c+12*num]+1;


                        elif (labels_im[i,j]==right_label):

                                if((dist_transform[i,j]>0 and dist_transform[i,j]<=3)):
                                    nlf = 0;
                                else:
                                    nlf = 1; 

                                for ncut in range(number_cut):
                                    if(i >= top_left +(height_left/3)*(ncut) and i <= top_left+ (height_left/3)*(ncut+1)):
                                        nlf_c = nlf + 2*ncut;
                                        for num in range(number_types):
                                            sum_all[nlf_c+6+12*num] = sum_all[nlf_c+6+12*num]+ data_images_current[i,j,num];
                                            num_all[nlf_c+6+12*num]= num_all[nlf_c+6+12*num]+1;



                mean=[];
                have_nan = False;
                for nlf in range(ns * 2 * number_types):
                    if(num_all[nlf]!=0):
                        mean.append(sum_all[nlf]/num_all[nlf])
                    else:
                        mean.append(np.nan);


                #if(not have_nan):
                #    total_mean.append(mean);
                total_mean.append(mean);

        total_mean=np.array(total_mean);
        total_mean=np.nanmean(total_mean,axis=0)
        #total_mean=np.mean(total_mean,axis=0)
        print(total_mean)
        name = files[num_file][0];
        colx = 0
        try:
            sheet1.write(rowx,colx, name)
            for nlf in range(ns * 2 * number_types): 
                sheet1.write(rowx,colx+nlf+1, total_mean[nlf])

            rowx = rowx+1;
        except:
            print('Something not right')
    except:
        print('Something not right')

excel.save("/home/peppermint/Desktop/NotAll_scan_2outin_3cut_all_type.xls")

















[5.27302293e-01 4.94995164e-01 4.62896001e-01 5.89875238e-01
 5.71980611e-01 6.20387517e-01 3.98520699e+00 3.84765907e+00
 3.68353272e+00 4.26175237e+00 4.19770820e+00 4.38850967e+00
 4.13261712e-01 4.08141397e-01 2.50464932e-01 3.81981542e-01
 3.47324557e-01 1.69871587e-01 4.52426592e+00 4.53502074e+00
 3.66629216e+00 4.40081574e+00 4.20690388e+00 3.22955487e+00
 2.21319930e-10 2.34446651e-10 2.37517839e-10 2.35409317e-10
 2.39152015e-10 2.41373086e-10 4.32348072e+00 4.49455574e+00
 4.57432773e+00 4.53320020e+00 4.59104241e+00 4.63235467e+00]
[5.15143270e-01 4.99665767e-01 4.41566027e-01 5.80962845e-01
 5.89748749e-01 6.01269502e-01 3.91695060e+00 3.87035346e+00
 3.53723077e+00 4.22882302e+00 4.29642570e+00 4.28103986e+00
 3.88926288e-01 3.58120668e-01 2.21611622e-01 3.91343873e-01
 3.28970564e-01 1.57738500e-01 4.36960326e+00 4.27771664e+00
 3.40530458e+00 4.43989288e+00 4.11342199e+00 3.07776387e+00
 2.64337330e-10 2.90086352e-10 2.64538204e-10 2.84871235e-10
 2.93830917e-10 2.70354

[2.41634858e-01 2.42784356e-01 1.53509218e-01 2.05219973e-01
 2.16484539e-01 1.70082930e-01 2.41037886e+00 2.50553906e+00
 1.98668367e+00 2.17077472e+00 2.31359303e+00 2.00650039e+00
 1.77226758e-01 1.84549914e-01 8.86418734e-02 1.56645023e-01
 1.58648586e-01 8.20542409e-02 2.57148824e+00 2.81809293e+00
 2.00155766e+00 2.24961803e+00 2.52087651e+00 1.90785092e+00
 4.51508231e-11 6.22192924e-11 5.05547559e-11 4.11997391e-11
 5.08804710e-11 4.97709115e-11 2.64443881e+00 3.08896662e+00
 2.81766398e+00 2.55449506e+00 2.79516137e+00 2.79482483e+00]
[2.07703008e-01 2.09073474e-01 1.05133371e-01 2.26331230e-01
 2.22344095e-01 1.25808969e-01 2.27070103e+00 2.38199425e+00
 1.71898600e+00 2.38659534e+00 2.40689238e+00 1.81368152e+00
 1.46612001e-01 1.57710135e-01 5.47189152e-02 1.56893841e-01
 1.32604223e-01 4.31575121e-02 2.48036723e+00 2.73687546e+00
 1.76673212e+00 2.63888004e+00 2.61085438e+00 1.72774832e+00
 7.03564776e-11 8.82207551e-11 5.71582293e-11 7.38858915e-11
 8.55776557e-11 6.50455

[7.94400890e-01 7.60132264e-01 7.21915258e-01 9.15182781e-01
 9.59317655e-01 9.38970430e-01 5.15996100e+00 5.02047902e+00
 4.80181976e+00 5.73468941e+00 5.91682343e+00 5.84011159e+00
 1.49709597e-01 1.67552699e-01 8.14644526e-02 1.20667744e-01
 1.39780864e-01 4.86305851e-02 3.00306116e+00 3.15109300e+00
 2.57171242e+00 2.90155658e+00 3.02246713e+00 2.36650398e+00
 2.97321069e-10 3.07582358e-10 3.07298902e-10 3.25084090e-10
 3.42479213e-10 3.23175988e-10 4.43486360e+00 4.54180387e+00
 4.58161235e+00 4.69900372e+00 4.92899016e+00 4.70672755e+00]
[5.79469743e-01 6.91681213e-01 6.04259203e-01 5.72569745e-01
 6.98855196e-01 6.40382471e-01 4.07804330e+00 4.69609052e+00
 4.15239229e+00 4.07892029e+00 4.71857384e+00 4.35027955e+00
 4.75155569e-01 4.38164309e-01 2.76959529e-01 4.36288387e-01
 3.87413811e-01 1.97870017e-01 4.30526202e+00 4.54041040e+00
 3.30733087e+00 4.08439186e+00 4.22816449e+00 3.01315433e+00
 9.22998805e-11 1.29423645e-10 8.52001451e-11 9.68496901e-11
 1.21441077e-10 9.51513

[7.87006363e-01 7.78107222e-01 7.76500362e-01 8.01137515e-01
 8.69505359e-01 1.01424384e+00 4.72952193e+00 4.67256766e+00
 4.63252494e+00 4.72259232e+00 4.94703008e+00 5.46211542e+00
 1.93069335e-01 1.72047369e-01 6.26276132e-02 2.27755411e-01
 1.80357022e-01 3.15945273e-02 3.17263283e+00 3.05598583e+00
 2.41048890e+00 3.39428412e+00 3.10698903e+00 2.20723947e+00
 2.66666436e-10 2.77216861e-10 2.64763639e-10 2.84726806e-10
 2.81576906e-10 2.61797374e-10 4.66674692e+00 4.80093784e+00
 4.70236849e+00 4.90938087e+00 4.87718845e+00 4.66203533e+00]
[9.34462466e-01 9.95978350e-01 7.78387180e-01 8.94854217e-01
 1.03436433e+00 9.11309915e-01 5.15049414e+00 5.45998561e+00
 4.61949237e+00 5.00681724e+00 5.59864478e+00 5.07711929e+00
 9.41660501e-02 1.25829155e-01 5.46769515e-02 8.32364182e-02
 8.91502502e-02 2.84982534e-02 2.49113402e+00 2.75926356e+00
 2.31698904e+00 2.41607479e+00 2.57780876e+00 2.12074619e+00
 3.60526203e-10 3.99966916e-10 4.01690894e-10 3.44902340e-10
 4.36246469e-10 3.88451

[1.03308707e+00 8.68714058e-01 8.02884251e-01 9.32213911e-01
 8.60571809e-01 9.53645639e-01 5.56028496e+00 4.98146793e+00
 4.72755312e+00 5.19690047e+00 4.96469238e+00 5.24513650e+00
 2.36395610e-01 2.37087060e-01 1.25543531e-01 2.96474219e-01
 2.48535202e-01 7.73613539e-02 3.36036346e+00 3.37355348e+00
 2.73763126e+00 3.70179614e+00 3.46247798e+00 2.45262718e+00
 2.10711011e-10 2.27325015e-10 2.15876027e-10 2.21594115e-10
 2.26409036e-10 2.14379882e-10 4.19917994e+00 4.44044300e+00
 4.31460828e+00 4.36688569e+00 4.40672030e+00 4.28259499e+00]
[8.51018407e-01 8.49853603e-01 7.95349944e-01 8.18068281e-01
 8.26760703e-01 8.34829092e-01 4.88344978e+00 4.89602533e+00
 4.58946415e+00 4.70385153e+00 4.78315546e+00 4.71274114e+00
 1.87400645e-01 1.75877634e-01 7.84711838e-02 1.77185991e-01
 1.72380818e-01 6.16601578e-02 3.06768469e+00 3.07802959e+00
 2.35242436e+00 3.01270898e+00 3.03496518e+00 2.22789252e+00
 3.43311999e-10 4.54508342e-10 3.45700151e-10 3.67664618e-10
 4.40311478e-10 3.39259

[9.62367231e-01 1.02440875e+00 8.42615683e-01 1.01885610e+00
 1.12729913e+00 1.00021307e+00 5.14123797e+00 5.44351546e+00
 4.68403299e+00 5.45377762e+00 5.84954953e+00 5.33727732e+00
 3.69896946e-01 4.03456943e-01 2.85686772e-01 3.53507117e-01
 3.37867343e-01 2.03884538e-01 3.76205922e+00 4.07310786e+00
 3.30768183e+00 3.81469608e+00 3.80751936e+00 3.02273878e+00
 1.18763630e-10 1.40413066e-10 1.20006239e-10 1.35443673e-10
 1.40651780e-10 1.42301385e-10 3.63105252e+00 4.01312749e+00
 3.68227243e+00 3.93044337e+00 4.00901383e+00 4.06343827e+00]
[5.98896165e-01 5.46377243e-01 5.13340110e-01 6.78935258e-01
 6.41801666e-01 6.20061557e-01 4.00248792e+00 3.83151846e+00
 3.70070362e+00 4.29900717e+00 4.12365269e+00 4.03926164e+00
 2.09951354e-01 2.01842359e-01 1.46763760e-01 2.30550046e-01
 2.32413685e-01 1.35143553e-01 3.26265371e+00 3.22106865e+00
 2.87335086e+00 3.33673014e+00 3.34517172e+00 2.82692435e+00
 2.24811259e-10 2.26565283e-10 2.11172815e-10 2.20066701e-10
 2.10116834e-10 2.19163

[7.93204170e-01 8.43273446e-01 9.05107990e-01 9.76957125e-01
 1.04406297e+00 1.14983321e+00 4.53049715e+00 4.85688656e+00
 5.02041858e+00 5.17730014e+00 5.59214498e+00 5.91390312e+00
 2.73052342e-01 2.64716424e-01 1.40669115e-01 3.06262287e-01
 2.85244393e-01 1.26746381e-01 3.25285799e+00 3.46438352e+00
 2.73096516e+00 3.36032837e+00 3.57430098e+00 2.69169405e+00
 2.10901200e-10 2.72342418e-10 2.33395637e-10 2.04220821e-10
 2.80595223e-10 2.49286317e-10 3.68249446e+00 4.28975885e+00
 3.87440544e+00 3.60977685e+00 4.36681281e+00 4.04472348e+00]
[5.21557408e-01 4.54765610e-01 5.40556639e-01 4.48129096e-01
 4.44762273e-01 5.49083920e-01 3.45712156e+00 3.38890148e+00
 3.70871881e+00 3.39868353e+00 3.41907267e+00 3.74468890e+00
 4.02861628e-01 3.25787793e-01 2.04223614e-01 2.94278368e-01
 2.85142626e-01 1.91790291e-01 3.43288858e+00 3.57642475e+00
 3.04362558e+00 3.46864037e+00 3.57166197e+00 3.00760376e+00
 7.85261310e-11 8.50021148e-11 8.88426012e-11 8.40119720e-11
 9.35792458e-11 9.32368

[6.40056562e-01 6.35371246e-01 6.74161476e-01 5.71383613e-01
 6.26548598e-01 7.97531637e-01 4.02829988e+00 4.01564221e+00
 4.02663961e+00 3.77218802e+00 4.04104795e+00 4.59549407e+00
 2.03955977e-01 1.74941095e-01 1.82669917e-01 2.46361577e-01
 1.98323646e-01 1.30677579e-01 2.98570970e+00 2.83767778e+00
 2.63030135e+00 3.16339656e+00 3.05362599e+00 2.59929174e+00
 6.80366381e-11 7.13432403e-11 7.04805717e-11 6.36265081e-11
 7.46484888e-11 6.99613021e-11 3.31880263e+00 3.40722601e+00
 3.39613378e+00 3.22118856e+00 3.49590952e+00 3.38292230e+00]
[5.56831849e-01 4.65298898e-01 4.65500670e-01 4.94326029e-01
 4.40228733e-01 5.07230506e-01 3.81443988e+00 3.48507837e+00
 3.43539898e+00 3.57945834e+00 3.34112037e+00 3.59885081e+00
 2.20659507e-01 2.29775263e-01 1.63579356e-01 2.30953280e-01
 2.01275994e-01 1.21524361e-01 3.27398051e+00 3.31556105e+00
 2.89443019e+00 3.30586531e+00 3.09442961e+00 2.67431075e+00
 1.55834741e-10 1.57584118e-10 1.48585504e-10 1.48142329e-10
 1.45920675e-10 1.56959

[8.04793194e-01 7.92302154e-01 7.31418754e-01 8.40972759e-01
 8.09633064e-01 6.77834624e-01 4.67358393e+00 4.65470991e+00
 4.45157814e+00 4.84113444e+00 4.70231855e+00 4.15949843e+00
 4.41013243e-01 4.72867436e-01 3.39026298e-01 4.53409178e-01
 4.19040972e-01 2.64021441e-01 4.33359431e+00 4.54324779e+00
 3.87384328e+00 4.43155338e+00 4.24327256e+00 3.34755726e+00
 2.56083959e-10 2.68472722e-10 2.67377569e-10 2.70317609e-10
 2.58980454e-10 2.21242379e-10 4.45959432e+00 4.57200360e+00
 4.58328358e+00 4.62042909e+00 4.47568385e+00 4.07920331e+00]
[8.04793194e-01 7.92302154e-01 7.31418754e-01 8.40972759e-01
 8.09633064e-01 6.77834624e-01 4.67358393e+00 4.65470991e+00
 4.45157814e+00 4.84113444e+00 4.70231855e+00 4.15949843e+00
 4.41013243e-01 4.72867436e-01 3.39026298e-01 4.53409178e-01
 4.19040972e-01 2.64021441e-01 4.33359431e+00 4.54324779e+00
 3.87384328e+00 4.43155338e+00 4.24327256e+00 3.34755726e+00
 2.56083959e-10 2.68472722e-10 2.67377569e-10 2.70317609e-10
 2.58980454e-10 2.21242

[9.99260875e-01 9.07748319e-01 7.97464683e-01 8.59445993e-01
 8.12263886e-01 7.05788827e-01 5.39524950e+00 5.06211941e+00
 4.62503061e+00 4.88420550e+00 4.76899985e+00 4.36418898e+00
 2.64309471e-01 2.49435890e-01 1.18918468e-01 2.73497354e-01
 2.59987272e-01 1.43974162e-01 3.50268264e+00 3.45084354e+00
 2.65948409e+00 3.53848975e+00 3.46699811e+00 2.83297320e+00
 3.52189216e-10 3.57586279e-10 3.30646793e-10 3.56472508e-10
 3.48827328e-10 3.55632617e-10 4.11637654e+00 4.13673633e+00
 3.99599942e+00 4.18100360e+00 4.09036035e+00 4.17314742e+00]
[9.82691562e-01 8.70821079e-01 7.08444349e-01 8.45886322e-01
 7.95341925e-01 7.03991999e-01 5.29205449e+00 4.92416623e+00
 4.23926508e+00 4.79431157e+00 4.68876284e+00 4.29703971e+00
 3.20712888e-01 2.63984949e-01 1.23225320e-01 3.33890427e-01
 3.04290001e-01 1.63294533e-01 3.71648167e+00 3.48152525e+00
 2.60603879e+00 3.74707853e+00 3.64135496e+00 2.90790413e+00
 2.85494114e-10 3.12954951e-10 2.81169337e-10 2.93872554e-10
 3.06865530e-10 3.08982

[7.33694586e-01 6.84965333e-01 6.93797231e-01 4.88710832e-01
 6.55625523e-01 6.63059993e-01 4.39486594e+00 4.24252126e+00
 4.28431185e+00 3.31734837e+00 4.09083271e+00 4.02318304e+00
 2.04381332e-01 2.09528064e-01 1.56137657e-01 1.06442772e-01
 1.09700787e-01 6.29544059e-02 3.06752712e+00 3.11417995e+00
 2.83139610e+00 2.23716342e+00 2.54377443e+00 2.15104829e+00
 2.27918592e-10 2.71392551e-10 2.58268107e-10 1.92818541e-10
 2.48915859e-10 2.25731389e-10 3.50501308e+00 3.87796804e+00
 3.76165581e+00 3.26253991e+00 3.68748918e+00 3.50818988e+00]
[5.47664218e-01 5.38199921e-01 5.71779404e-01 4.05888751e-01
 5.73600720e-01 5.68646539e-01 3.63471948e+00 3.61886463e+00
 3.82081012e+00 2.95999198e+00 3.80938399e+00 3.69344016e+00
 2.01920863e-01 2.08936244e-01 1.65607360e-01 1.24741168e-01
 1.51420465e-01 5.47013057e-02 3.00273076e+00 3.07550333e+00
 2.93484163e+00 2.39325455e+00 2.81769245e+00 2.12441260e+00
 2.62712000e-10 2.92808993e-10 3.36327131e-10 2.24359476e-10
 3.29568431e-10 2.79283

[6.07261330e-01 6.43293821e-01 6.18761861e-01 6.13180163e-01
 6.83389211e-01 7.12943099e-01 3.97990058e+00 4.13524023e+00
 3.99893673e+00 3.99186812e+00 4.29287219e+00 4.41440999e+00
 2.03021884e-01 1.86562399e-01 1.12516551e-01 1.77770352e-01
 1.73087701e-01 8.72165894e-02 3.10283340e+00 3.07914603e+00
 2.63844110e+00 2.97978950e+00 2.99251610e+00 2.50225745e+00
 2.18005195e-10 2.28431667e-10 2.22954524e-10 2.18774640e-10
 2.33263974e-10 2.19367011e-10 3.87837758e+00 3.97983018e+00
 3.92062370e+00 3.92923024e+00 4.04895425e+00 3.87311177e+00]
[6.68941717e-01 6.67425438e-01 5.90676675e-01 5.40529113e-01
 6.60529223e-01 6.31202232e-01 4.15474747e+00 4.18554207e+00
 3.80773225e+00 3.71033631e+00 4.18374416e+00 4.04825322e+00
 2.22010267e-01 2.47098786e-01 1.97689993e-01 2.03912244e-01
 1.93993702e-01 9.43233638e-02 3.08776813e+00 3.32048301e+00
 2.89138020e+00 3.08422102e+00 3.08990023e+00 2.46669803e+00
 2.13964061e-10 2.23941621e-10 1.82853484e-10 2.31481440e-10
 2.35946850e-10 2.10422

[8.94736485e-01 9.21019365e-01 9.88500626e-01 1.08372191e+00
 1.13795175e+00 1.03625861e+00 5.04516963e+00 5.15332445e+00
 5.37249635e+00 5.76288770e+00 5.94807204e+00 5.52832714e+00
 2.48539274e-01 2.87157394e-01 2.26592318e-01 2.29063824e-01
 2.13278108e-01 1.52521490e-01 3.43860878e+00 3.63345816e+00
 3.31164037e+00 3.36609430e+00 3.26733947e+00 2.90471759e+00
 4.15919956e-10 4.27449977e-10 4.37367357e-10 4.53851404e-10
 4.36745240e-10 4.48742612e-10 4.31651655e+00 4.40982260e+00
 4.49431440e+00 4.55699390e+00 4.44991906e+00 4.57658159e+00]
[9.43719489e-01 9.00177221e-01 9.39900398e-01 1.07651583e+00
 1.12345871e+00 1.03679718e+00 5.22492378e+00 5.08201057e+00
 5.15923748e+00 5.71128931e+00 5.84212412e+00 5.55244733e+00
 2.52296542e-01 2.63350323e-01 2.21295831e-01 2.25780288e-01
 1.89093199e-01 1.38642377e-01 3.45254650e+00 3.53412166e+00
 3.26837613e+00 3.31399849e+00 3.15193080e+00 2.84548596e+00
 3.55865951e-10 4.01151207e-10 3.70608397e-10 3.96020921e-10
 3.90852600e-10 4.05976

[7.30174484e-01 8.45584014e-01 7.36187956e-01 7.10762681e-01
 7.52212569e-01 6.78681848e-01 4.29539679e+00 4.84378373e+00
 4.35383555e+00 4.33120451e+00 4.49075272e+00 4.06850500e+00
 9.10916411e-02 1.11510999e-01 3.32604193e-02 1.51397295e-01
 1.79679206e-01 7.61985796e-02 2.32689372e+00 2.60680932e+00
 2.05335884e+00 2.84397721e+00 3.00984958e+00 2.26354925e+00
 2.55581716e-10 3.37070498e-10 3.35826847e-10 3.42346269e-10
 3.63725549e-10 3.17013976e-10 3.45781397e+00 4.05285208e+00
 4.09144723e+00 4.11809068e+00 4.26161225e+00 3.97027975e+00]
[8.06590983e-01 8.92583492e-01 7.77279414e-01 7.59624790e-01
 8.26378264e-01 7.93566956e-01 4.63007756e+00 5.05345366e+00
 4.54798099e+00 4.55129779e+00 4.80908131e+00 4.57958090e+00
 2.73073212e-01 2.22577898e-01 1.13893423e-01 2.72300686e-01
 2.58566054e-01 1.45472952e-01 3.36544143e+00 3.28867498e+00
 2.64749332e+00 3.53134950e+00 3.52136707e+00 2.80358956e+00
 2.65425626e-10 3.93875480e-10 3.88407186e-10 3.67602256e-10
 4.09069998e-10 4.00461

[1.16003811e+00 1.26023361e+00 1.31375625e+00 1.33069169e+00
 6.00155702e+00 6.38016790e+00 6.53582352e+00 6.63568910e+00
 1.88395674e-01 2.53522587e-01 2.51299585e-01 3.32515711e-01
 3.06852644e+00 3.45089118e+00 3.35502081e+00 3.83619387e+00
 1.70518137e-10 1.85914247e-10 1.67682724e-10 1.95565009e-10
 4.23678051e+00 4.48856358e+00 4.20774015e+00 4.67069038e+00]
[1.29006337e+00 1.39922766e+00 1.30743948e+00 1.41153393e+00
 6.43298654e+00 6.87548691e+00 6.45961689e+00 6.90640353e+00
 2.29032148e-01 2.82604142e-01 2.28609250e-01 3.17269607e-01
 3.23784174e+00 3.59068547e+00 3.16347321e+00 3.72929317e+00
 1.42349158e-10 1.56084518e-10 1.34908122e-10 1.64348152e-10
 4.04448577e+00 4.28851609e+00 3.92957586e+00 4.47190714e+00]
[6.26091688e-01 6.61430931e-01 6.33053581e-01 6.79632623e-01
 4.42816529e+00 4.60117644e+00 4.44093834e+00 4.62935571e+00
 2.63116492e-01 2.81005657e-01 2.23384702e-01 2.29040116e-01
 3.73745232e+00 3.87558560e+00 3.52277379e+00 3.60590891e+00
 3.18168917e-10 3.8695

[6.46416179e-01 7.10864452e-01 6.26915490e-01 7.49210268e-01
 4.36479999e+00 4.75352733e+00 4.29888427e+00 4.91785463e+00
 3.89236151e-01 4.41736895e-01 3.97608050e-01 4.55222639e-01
 3.92604907e+00 4.36317814e+00 3.91590225e+00 4.45170307e+00
 9.27851302e-11 1.15625496e-10 8.89299409e-11 1.12196123e-10
 3.44528546e+00 3.97548047e+00 3.35607034e+00 3.88399304e+00]
[7.47670095e-01 9.46007461e-01 7.87443601e-01 1.04669073e+00
 4.72268713e+00 5.77561988e+00 4.84466477e+00 6.23326094e+00
 4.77132332e-01 5.59839640e-01 4.39300784e-01 5.79442365e-01
 4.06807186e+00 4.94924409e+00 3.97350179e+00 5.06220958e+00
 1.03373734e-10 1.54150977e-10 1.05539340e-10 1.58896541e-10
 3.06614938e+00 3.90891256e+00 3.11400905e+00 3.99176498e+00]
[4.67673906e-01 5.54223313e-01 5.32835774e-01 5.94509764e-01
 3.60968243e+00 4.11305900e+00 3.94098316e+00 4.28641221e+00
 2.80747052e-01 3.20279542e-01 2.79785082e-01 2.81364061e-01
 3.59154373e+00 4.05557578e+00 3.66051345e+00 3.83761831e+00
 1.01309030e-10 1.5193

[1.17017045e+00 1.20672888e+00 1.14037367e+00 1.14471020e+00
 6.05667767e+00 6.20143573e+00 5.96058771e+00 5.99585068e+00
 1.29542777e-01 1.79363514e-01 9.62403876e-02 1.10270366e-01
 2.78869460e+00 3.08657262e+00 2.58436589e+00 2.67510123e+00
 3.00243716e-10 3.28793119e-10 2.79326033e-10 3.31792514e-10
 4.19090429e+00 4.54006004e+00 4.07466295e+00 4.58051384e+00]
[6.72601372e-01 6.93053508e-01 7.44077381e-01 7.45488716e-01
 4.20352644e+00 4.24246734e+00 4.53436691e+00 4.59609646e+00
 2.15119308e-01 2.19207593e-01 1.76633423e-01 1.64756107e-01
 3.26926147e+00 3.34164810e+00 3.08062279e+00 3.02519379e+00
 4.39719508e-10 5.72079110e-10 4.34746630e-10 5.91870141e-10
 4.35321110e+00 5.35995173e+00 4.33204979e+00 5.53384518e+00]
[7.95743658e-01 8.61753403e-01 8.61255244e-01 8.75691553e-01
 4.71076367e+00 4.94784778e+00 4.94568613e+00 4.99844014e+00
 2.61072620e-01 2.93960400e-01 2.37966557e-01 2.48782807e-01
 3.49438866e+00 3.69191862e+00 3.39061781e+00 3.46580806e+00
 1.75788705e-10 1.9023

[4.50825224e-01 4.20497949e-01 4.23985790e-01 4.41946106e-01
 3.39863257e+00 3.32718832e+00 3.30435821e+00 3.42127272e+00
 2.23415069e-01 2.17595201e-01 2.15071416e-01 2.01977659e-01
 3.04543776e+00 3.12583572e+00 3.01577374e+00 3.08058462e+00
 5.43922315e-11 5.87954449e-11 5.41419998e-11 6.32990307e-11
 3.85875128e+00 4.04606948e+00 3.84371671e+00 4.23043058e+00]
[8.03355983e-01 7.86007423e-01 9.80433791e-01 9.79795558e-01
 4.71914249e+00 4.67717071e+00 5.35503993e+00 5.37984636e+00
 2.58666505e-01 3.51583799e-01 2.62803425e-01 3.09498301e-01
 3.42257587e+00 3.94829672e+00 3.45823141e+00 3.73818335e+00
 1.08201879e-10 1.18314378e-10 1.09752919e-10 1.25336160e-10
 4.29068725e+00 4.58451261e+00 4.33885168e+00 4.76568866e+00]
[9.06395448e-01 1.01341259e+00 9.76090057e-01 1.03866627e+00
 5.04370855e+00 5.49060161e+00 5.30584381e+00 5.57601760e+00
 2.04931982e-01 2.47509303e-01 1.88249499e-01 2.30215563e-01
 3.07138811e+00 3.41056107e+00 3.03376986e+00 3.32616841e+00
 1.21637010e-10 1.4282

[1.04752004e+00 1.05908058e+00 9.95691807e-01 9.88892261e-01
 5.58411695e+00 5.64636065e+00 5.40325781e+00 5.37967066e+00
 4.89335776e-01 5.40197118e-01 5.30813563e-01 6.16858985e-01
 4.47625631e+00 4.76331163e+00 4.66480828e+00 5.10309772e+00
 1.44019243e-10 1.60620885e-10 1.49348819e-10 1.59081704e-10
 4.32655342e+00 4.67381790e+00 4.42498346e+00 4.62067444e+00]
Something not right
[1.13133201e+00 1.18389661e+00 1.24562948e+00 1.30911062e+00
 5.87154539e+00 6.10411562e+00 6.28397170e+00 6.55683864e+00
 1.99496523e-01 2.22984386e-01 2.27629696e-01 2.68176659e-01
 3.06033088e+00 3.26973350e+00 3.24388038e+00 3.51945565e+00
 1.10595896e-10 1.39317221e-10 1.07398753e-10 1.43191715e-10
 4.07539078e+00 4.77696973e+00 3.99882593e+00 4.87709025e+00]
[6.35047344e-01 6.71367768e-01 8.34324011e-01 1.00187680e+00
 3.80741012e+00 3.97643811e+00 4.62583659e+00 5.35304739e+00
 1.17314199e-01 1.86733210e-01 1.48328833e-01 1.98784090e-01
 2.27115267e+00 2.65180961e+00 2.60821098e+00 3.08785999e+00
 2

[5.33852159e-01 5.19989704e-01 4.34980259e-01 4.27653767e-01
 3.74385847e+00 3.73461855e+00 3.38513701e+00 3.35337698e+00
 3.05790624e-01 3.63092505e-01 2.76608744e-01 3.17297612e-01
 3.72980404e+00 4.05217383e+00 3.58485345e+00 3.84563021e+00
 2.26992086e-10 2.48716560e-10 2.27627412e-10 2.49973694e-10
 4.70804139e+00 5.02214322e+00 4.72664087e+00 5.04947934e+00]
[5.54833001e-01 6.02601430e-01 5.24093810e-01 5.75968337e-01
 3.76381740e+00 3.99944960e+00 3.65406956e+00 3.91972560e+00
 3.34271765e-01 3.94568994e-01 3.73803249e-01 4.53860391e-01
 3.73275346e+00 4.13258514e+00 3.94110377e+00 4.43686065e+00
 1.11435330e-10 1.19519016e-10 1.06644836e-10 1.25552850e-10
 3.97069483e+00 4.16142379e+00 3.88588973e+00 4.28020726e+00]
[5.33852159e-01 5.19989704e-01 4.34980259e-01 4.27653767e-01
 3.74385847e+00 3.73461855e+00 3.38513701e+00 3.35337698e+00
 3.05790624e-01 3.63092505e-01 2.76608744e-01 3.17297612e-01
 3.72980404e+00 4.05217383e+00 3.58485345e+00 3.84563021e+00
 2.26992086e-10 2.4871

[1.12430485e+00 1.19163433e+00 1.15457746e+00 1.16045435e+00
 5.62101211e+00 6.07527028e+00 5.86676944e+00 5.91640376e+00
 2.71285850e-01 2.65462048e-01 2.35544172e-01 2.70116548e-01
 3.11661361e+00 3.40620137e+00 3.11183940e+00 3.42230770e+00
 9.89806782e-11 1.25947519e-10 1.08774789e-10 1.31704566e-10
 3.68602065e+00 4.27231436e+00 3.89660372e+00 4.39986131e+00]
[4.11577129e-01 4.34060749e-01 4.39681536e-01 4.28891477e-01
 3.26683765e+00 3.39224907e+00 3.39109324e+00 3.37587148e+00
 1.27402319e-01 1.65721839e-01 1.30203383e-01 1.70527643e-01
 2.69385229e+00 3.00203392e+00 2.73862594e+00 2.99196868e+00
 1.11540957e-10 1.26393120e-10 1.18900707e-10 1.17483872e-10
 3.67468922e+00 3.96815280e+00 3.84930894e+00 3.81670089e+00]
[4.50189176e-01 6.05606681e-01 5.01530331e-01 5.66167339e-01
 3.21854985e+00 3.94078217e+00 3.39743998e+00 3.70004030e+00
 1.39685609e-01 2.08783515e-01 1.11841100e-01 1.68510587e-01
 2.52321842e+00 3.17559799e+00 2.36790263e+00 2.81891651e+00
 1.69489059e-10 2.5226

[1.06762478e+00 1.17822516e+00 1.17795016e+00 1.22419797e+00
 5.64625776e+00 6.08400354e+00 6.07657663e+00 6.25895254e+00
 1.70317357e-01 2.17223349e-01 2.35749408e-01 2.84897058e-01
 2.96222948e+00 3.26308728e+00 3.34353295e+00 3.63589901e+00
 2.61318125e-10 3.23996480e-10 2.77131513e-10 3.25604834e-10
 4.23418990e+00 4.95843438e+00 4.41330169e+00 4.98670055e+00]
[1.08488173e+00 1.15817774e+00 1.20508087e+00 1.22655508e+00
 5.73477931e+00 6.01001884e+00 6.17925140e+00 6.25703330e+00
 1.11960967e-01 1.44670186e-01 1.70060619e-01 1.94254042e-01
 2.68523485e+00 2.89192878e+00 3.01281010e+00 3.18482424e+00
 3.65602046e-10 4.24018845e-10 3.54178891e-10 4.33894023e-10
 4.39530964e+00 4.94245564e+00 4.33501198e+00 5.04513657e+00]
[1.24582893e+00 1.30522938e+00 1.35330656e+00 1.37189840e+00
 6.33122596e+00 6.54628335e+00 6.73268136e+00 6.78181798e+00
 1.45353531e-01 1.84967368e-01 1.86758057e-01 2.46683986e-01
 2.86238750e+00 3.10654261e+00 3.10988399e+00 3.45494686e+00
 2.78304583e-10 3.1704

[6.86202399e-01 7.01840910e-01 5.44634063e-01 6.45242796e-01
 4.64329024e+00 4.76198033e+00 3.95785930e+00 4.51090443e+00
 2.63236025e-01 3.08907500e-01 2.65135703e-01 2.81868919e-01
 3.61378451e+00 4.00653208e+00 3.49993813e+00 3.85244390e+00
 1.60670255e-10 2.11313321e-10 1.41785755e-10 2.08922946e-10
 3.94220380e+00 4.85315169e+00 3.63988825e+00 4.80960603e+00]
[6.86202399e-01 7.01840910e-01 5.44634063e-01 6.45242796e-01
 4.64329024e+00 4.76198033e+00 3.95785930e+00 4.51090443e+00
 2.63236025e-01 3.08907500e-01 2.65135703e-01 2.81868919e-01
 3.61378451e+00 4.00653208e+00 3.49993813e+00 3.85244390e+00
 1.60670255e-10 2.11313321e-10 1.41785755e-10 2.08922946e-10
 3.94220380e+00 4.85315169e+00 3.63988825e+00 4.80960603e+00]
[6.84762631e-01 8.10274292e-01 6.35187604e-01 7.35743462e-01
 4.14770320e+00 4.71161397e+00 4.00725416e+00 4.48798448e+00
 1.41576175e-01 1.32858331e-01 1.22822795e-01 1.43736500e-01
 2.63185344e+00 2.77346724e+00 2.58885123e+00 2.86736857e+00
 2.42356217e-10 3.5895

[4.85826953e-01 5.11796398e-01 3.64664152e-01 3.87426815e-01
 3.30059417e-01 3.57343497e-01 5.59547378e-01 5.75590909e-01
 4.64324073e-01 4.72811927e-01 3.70034819e-01 3.67072995e-01
 3.74635354e+00 3.91641797e+00 3.19853276e+00 3.34752629e+00
 2.94322946e+00 3.22304308e+00 4.11342822e+00 4.18823579e+00
 3.57341198e+00 3.74210080e+00 3.24631316e+00 3.25366663e+00
 2.67240491e-01 2.84567085e-01 2.44472520e-01 2.77326273e-01
 1.78201888e-01 1.58493189e-01 2.39179261e-01 2.28886922e-01
 2.67656031e-01 1.72808941e-01 1.53931272e-01 1.19283051e-01
 3.56523968e+00 3.83445955e+00 3.42546561e+00 3.75493027e+00
 2.76445157e+00 3.04032810e+00 3.53110936e+00 3.57258109e+00
 3.33682895e+00 3.15048489e+00 2.89334641e+00 2.79835707e+00
 6.97897987e-11 9.05373063e-11 7.06011745e-11 8.32262286e-11
 6.41591722e-11 8.42190902e-11 7.96649011e-11 9.44834130e-11
 6.91973265e-11 8.90570157e-11 7.46931583e-11 9.85398707e-11
 3.60324328e+00 4.29913674e+00 3.64481616e+00 4.07392398e+00
 3.49025017e+00 4.097257

[2.87882273e-01 4.52606457e-01 3.71337527e-01 4.53389961e-01
 2.40323080e-01 3.72283159e-01 2.66522366e-01 4.45563583e-01
 3.34419201e-01 4.43825373e-01 2.48832841e-01 3.76011178e-01
 2.67409393e+00 3.67953082e+00 3.20335906e+00 3.69763823e+00
 2.43800561e+00 3.23605337e+00 2.57290482e+00 3.67139438e+00
 3.00491441e+00 3.67341619e+00 2.49902899e+00 3.26154184e+00
 1.46963062e-01 1.73699092e-01 1.60915674e-01 1.52133505e-01
 6.51904315e-02 8.09667059e-02 1.35394564e-01 1.58028426e-01
 1.65930210e-01 1.60277906e-01 1.06420620e-01 1.21120847e-01
 2.61381292e+00 3.21725917e+00 2.99998475e+00 3.10223150e+00
 2.06280307e+00 2.52720217e+00 2.52065239e+00 3.15809968e+00
 2.94011898e+00 3.18094038e+00 2.35552791e+00 2.83380912e+00
 4.71498966e-10 9.46486062e-10 7.39416342e-10 9.14019814e-10
 4.67186835e-10 8.32043294e-10 4.38965507e-10 1.01048656e-09
 6.18533315e-10 9.62799906e-10 4.59826771e-10 8.66905631e-10
 2.82036688e+00 4.28136730e+00 3.60504744e+00 4.09459738e+00
 2.83742105e+00 3.891242

[4.95561448e-01 5.58025763e-01 5.66519745e-01 5.84450158e-01
 4.42909980e-01 3.85962845e-01 5.44538121e-01 5.18812687e-01
 6.50120771e-01 5.49836944e-01 3.51214072e-01 3.40857172e-01
 3.21268244e+00 3.52445190e+00 3.44657086e+00 3.50165225e+00
 2.85994466e+00 2.80084599e+00 3.51627879e+00 3.32922606e+00
 3.85297099e+00 3.36031961e+00 2.61067923e+00 2.74774204e+00
 5.86777630e-01 7.28616646e-01 3.20108282e-01 3.65686845e-01
 3.53734901e-01 3.14102996e-01 5.71299222e-01 6.44871720e-01
 3.21101910e-01 3.95764399e-01 2.64377004e-01 2.85566477e-01
 3.54106655e+00 4.22080283e+00 2.60371917e+00 2.77547207e+00
 2.47379166e+00 2.45078197e+00 3.75682494e+00 4.04609442e+00
 2.64797877e+00 2.80270422e+00 2.37382916e+00 2.47002188e+00
 4.30117244e-11 4.97711152e-11 4.46123533e-11 4.30639158e-11
 3.78823248e-11 4.25147845e-11 4.78257527e-11 4.97749245e-11
 4.82645507e-11 4.14734658e-11 3.96483018e-11 4.14005016e-11
 3.14662760e+00 3.41595209e+00 3.21531862e+00 3.13390254e+00
 2.93491728e+00 3.118572

[7.96888852e-01 8.98926787e-01 5.23822381e-01 6.94700709e-01
 4.60445929e-01 6.28429842e-01 7.66352854e-01 9.87029968e-01
 7.30075533e-01 8.82685260e-01 5.10005215e-01 6.97127532e-01
 5.12939795e+00 5.65362370e+00 3.80110176e+00 4.71462700e+00
 3.50114778e+00 4.41154919e+00 4.84450492e+00 6.00835941e+00
 4.69874014e+00 5.51648956e+00 3.76415637e+00 4.73081276e+00
 4.87214246e-01 4.54355466e-01 4.12706085e-01 4.75433221e-01
 2.95583812e-01 3.35731961e-01 2.70220650e-01 2.67505061e-01
 3.24519671e-01 3.83520508e-01 2.85890132e-01 3.20918055e-01
 4.72141618e+00 4.74607208e+00 4.06588872e+00 4.78418348e+00
 3.46388253e+00 4.09241590e+00 3.29549249e+00 3.62821068e+00
 3.60992852e+00 4.26028084e+00 3.49474676e+00 4.01089293e+00
 1.85572801e-10 2.70507897e-10 1.48732543e-10 2.27049014e-10
 1.45385793e-10 2.35307100e-10 1.75465396e-10 2.58408777e-10
 1.48816381e-10 2.39149214e-10 1.66916058e-10 2.46180932e-10
 3.46615822e+00 4.50424363e+00 3.08961344e+00 3.97213919e+00
 3.04955408e+00 4.067505

[4.92158870e-01 5.35496660e-01 4.46588707e-01 4.85365940e-01
 3.58534839e-01 4.40550823e-01 4.83596129e-01 5.41981239e-01
 4.44668644e-01 4.87792482e-01 4.75328135e-01 4.80768990e-01
 3.76196620e+00 4.02800606e+00 3.57773767e+00 3.80567004e+00
 3.05550157e+00 3.57921136e+00 3.70452309e+00 4.04120928e+00
 3.51616140e+00 3.79802697e+00 3.67081014e+00 3.75126677e+00
 1.81708097e-01 1.51256655e-01 1.51685993e-01 1.36894727e-01
 1.18503269e-01 1.07951084e-01 1.44091768e-01 1.27545211e-01
 1.26349175e-01 1.20432653e-01 1.11121687e-01 8.88154985e-02
 3.11983972e+00 3.12163756e+00 2.98396625e+00 3.00981398e+00
 2.50256072e+00 2.76650177e+00 2.89545062e+00 2.97886185e+00
 2.72800785e+00 2.86908591e+00 2.64095132e+00 2.62394704e+00
 4.84385466e-11 7.26937116e-11 5.57550497e-11 6.66380265e-11
 3.74421783e-11 6.37438374e-11 4.67753361e-11 7.13236615e-11
 4.68868604e-11 6.32121694e-11 4.78234043e-11 6.62415126e-11
 3.53527228e+00 4.72454022e+00 3.81127172e+00 4.38783862e+00
 3.08064272e+00 4.289962

[9.45999982e-01 1.15879653e+00 6.69033675e-01 7.45307238e-01
 4.44367863e-01 5.83143115e-01 9.76856370e-01 1.09802113e+00
 7.58460580e-01 1.00514208e+00 7.81699663e-01 1.08479211e+00
 5.00975395e+00 5.96941739e+00 4.04436633e+00 4.35928013e+00
 3.20465323e+00 3.80547181e+00 5.17942919e+00 5.67157840e+00
 4.22626078e+00 5.25934612e+00 4.32719809e+00 5.56318273e+00
 2.43653925e-01 2.80000577e-01 1.86420949e-01 1.87833532e-01
 1.12022980e-01 1.69542882e-01 3.10639290e-01 3.06024640e-01
 2.62597240e-01 3.08304197e-01 2.20744706e-01 3.06023091e-01
 3.10620854e+00 3.53885971e+00 2.82511672e+00 2.91546668e+00
 2.40763579e+00 2.82803130e+00 3.56041020e+00 3.59581787e+00
 3.00774162e+00 3.40555946e+00 2.82320990e+00 3.45834716e+00
 3.03505718e-10 4.34895887e-10 3.60700870e-10 4.55832644e-10
 3.66088803e-10 4.28217258e-10 3.52347316e-10 4.21242983e-10
 2.88271152e-10 3.51261137e-10 2.73481711e-10 3.21790216e-10
 2.77250201e+00 3.29118744e+00 3.04384325e+00 3.41155175e+00
 3.00725714e+00 3.264109

[1.01689365e+00 1.07540250e+00 9.01018604e-01 9.55038849e-01
 7.78039252e-01 8.24353607e-01 1.18886330e+00 1.21747016e+00
 1.08842966e+00 1.13934626e+00 8.38627876e-01 9.04699435e-01
 5.48110114e+00 5.70829047e+00 5.07582695e+00 5.27464265e+00
 4.63195111e+00 4.80213138e+00 6.16826351e+00 6.28628661e+00
 5.74687093e+00 5.96245142e+00 4.85946603e+00 5.06720282e+00
 7.90142221e-02 9.11945288e-02 1.94917402e-01 1.81609152e-01
 1.12016299e-01 1.17495354e-01 1.68153351e-01 1.94003302e-01
 3.42993513e-01 3.07207929e-01 1.51458007e-01 1.43633622e-01
 2.49213276e+00 2.58601695e+00 3.14793238e+00 3.08258646e+00
 2.74564815e+00 2.75152633e+00 3.04197853e+00 3.20274741e+00
 3.93752307e+00 3.79412181e+00 2.95402578e+00 2.94040988e+00
 4.68374238e-10 5.47972107e-10 4.44548869e-10 5.39276375e-10
 4.33761975e-10 5.71106497e-10 4.46021959e-10 5.53658830e-10
 4.33528568e-10 5.16389727e-10 4.24377180e-10 5.77773445e-10
 4.48004206e+00 5.09087922e+00 4.30392229e+00 5.01250469e+00
 4.25665395e+00 5.306246

[1.01068266e+00 1.04146557e+00 7.09558998e-01 8.25634786e-01
 9.06398925e-01 9.19949482e-01 8.86844288e-01 9.27261256e-01
 8.46738725e-01 8.99667375e-01 8.87648758e-01 9.35220950e-01
 5.50770838e+00 5.63265824e+00 4.35927717e+00 4.81449628e+00
 5.11352928e+00 5.16342572e+00 5.02218837e+00 5.16155537e+00
 4.88802970e+00 5.14053017e+00 5.05106212e+00 5.21859432e+00
 1.57248192e-01 2.13036984e-01 2.55084867e-01 2.91637085e-01
 1.20207812e-01 1.36433926e-01 2.24528708e-01 2.71173503e-01
 3.22753673e-01 3.30196818e-01 1.48637109e-01 1.95069390e-01
 2.93896994e+00 3.24493179e+00 3.41089232e+00 3.66646995e+00
 2.71933223e+00 2.85248632e+00 3.31767645e+00 3.58294218e+00
 3.80256250e+00 3.89738265e+00 2.90824201e+00 3.17712448e+00
 2.17245091e-10 2.39252871e-10 1.91812636e-10 2.35393777e-10
 2.08625160e-10 2.42294322e-10 2.05678214e-10 2.48800067e-10
 1.76092910e-10 2.39302292e-10 2.17013638e-10 2.38685479e-10
 4.28608849e+00 4.58063815e+00 3.96248407e+00 4.56945867e+00
 4.16583465e+00 4.618158

[5.84019157e-01 6.15053894e-01 5.35983870e-01 5.63278850e-01
 4.46273082e-01 4.89657237e-01 5.71508350e-01 6.13085400e-01
 5.48779752e-01 5.83193139e-01 5.08686438e-01 5.20001676e-01
 3.97307275e+00 4.13863614e+00 3.81123451e+00 3.95328685e+00
 3.42506782e+00 3.65317039e+00 3.90150770e+00 4.08087540e+00
 3.87048235e+00 4.02105211e+00 3.74484510e+00 3.79970364e+00
 2.75432522e-01 2.93414573e-01 2.65663106e-01 2.83376852e-01
 1.43072162e-01 1.70817971e-01 2.81302493e-01 2.84588026e-01
 2.66363669e-01 2.58372779e-01 1.72938585e-01 1.80439256e-01
 3.54198838e+00 3.71809866e+00 3.52158510e+00 3.63636124e+00
 2.83820333e+00 3.04120736e+00 3.59728240e+00 3.65390229e+00
 3.54105787e+00 3.48275377e+00 3.07535156e+00 3.08549249e+00
 3.39503599e-10 4.57895306e-10 3.81437563e-10 4.26383354e-10
 3.62773350e-10 4.34177488e-10 3.57310508e-10 4.62685653e-10
 4.09466527e-10 4.48865893e-10 4.13821429e-10 4.87837850e-10
 4.15873846e+00 5.19538727e+00 4.55143304e+00 4.89228016e+00
 4.39537564e+00 5.008099

[6.34304801e-01 6.25378535e-01 5.29059688e-01 5.52274080e-01
 4.46235316e-01 4.97261443e-01 7.40434351e-01 7.38361644e-01
 6.49007500e-01 6.82329983e-01 5.45486783e-01 5.97407366e-01
 4.10019371e+00 4.07442421e+00 3.75799525e+00 3.91175717e+00
 3.38189227e+00 3.68512505e+00 4.51481262e+00 4.50727414e+00
 4.12674484e+00 4.24431954e+00 3.78854314e+00 4.00853922e+00
 2.30285893e-01 2.43160368e-01 1.87506220e-01 1.97661994e-01
 1.32885431e-01 1.42648510e-01 2.63780108e-01 2.79899439e-01
 2.39589307e-01 2.56798276e-01 1.09933428e-01 1.34675530e-01
 3.37441845e+00 3.46141894e+00 3.13312745e+00 3.19707181e+00
 2.71878528e+00 2.91488153e+00 3.52376731e+00 3.64122001e+00
 3.36360224e+00 3.51250232e+00 2.64996213e+00 2.88369368e+00
 2.13362171e-10 2.33298545e-10 2.16618972e-10 2.33973236e-10
 1.84268497e-10 2.31962017e-10 2.18252850e-10 2.29722762e-10
 1.85926162e-10 2.34668973e-10 2.16694413e-10 2.55224869e-10
 4.32688942e+00 4.59681782e+00 4.31061745e+00 4.60098535e+00
 3.97608628e+00 4.632551

[9.06227541e-01 1.00346053e+00 8.15718259e-01 9.80533327e-01
 9.28664022e-01 9.90855969e-01 7.59870722e-01 1.06273407e+00
 9.33795082e-01 1.09361679e+00 8.56027561e-01 1.09996735e+00
 5.01241122e+00 5.44261434e+00 4.69864654e+00 5.36362468e+00
 5.10011902e+00 5.39872559e+00 4.32132820e+00 5.71002973e+00
 5.09918237e+00 5.80215297e+00 4.70454859e+00 5.82077474e+00
 2.11356887e-01 2.72054893e-01 2.65120034e-01 3.15019737e-01
 2.16006242e-01 2.61711413e-01 1.98062221e-01 2.65536365e-01
 3.42018816e-01 3.92794046e-01 2.32055518e-01 2.66637872e-01
 3.10006892e+00 3.58219973e+00 3.39763592e+00 3.78953033e+00
 3.14274873e+00 3.50877438e+00 2.82641966e+00 3.54920311e+00
 3.73492396e+00 4.17757448e+00 3.02960547e+00 3.56959447e+00
 1.82676185e-10 2.68727901e-10 1.82802821e-10 2.21593433e-10
 1.71282986e-10 2.35704370e-10 1.35356840e-10 2.83078763e-10
 1.66626078e-10 2.21513302e-10 1.44533908e-10 2.59915413e-10
 3.63390563e+00 4.61573921e+00 3.60770925e+00 4.03636124e+00
 3.49192611e+00 4.204883

[8.89513443e-01 8.58941405e-01 6.15765535e-01 7.13426692e-01
 6.07019197e-01 6.35320457e-01 1.02766212e+00 1.05179632e+00
 1.00033646e+00 1.04420537e+00 8.07504480e-01 8.68351621e-01
 5.00112116e+00 4.93385327e+00 3.91329123e+00 4.37388965e+00
 3.95276062e+00 4.12276390e+00 5.51600940e+00 5.64572911e+00
 5.32402526e+00 5.57212518e+00 4.68050739e+00 4.96922748e+00
 3.70001316e-01 4.31132563e-01 3.84390769e-01 4.62866730e-01
 2.28716978e-01 2.58050267e-01 4.54622369e-01 4.91701782e-01
 4.10905722e-01 4.46672431e-01 2.61640300e-01 3.62356169e-01
 3.98988207e+00 4.36188049e+00 3.81259547e+00 4.41333740e+00
 3.20129082e+00 3.44239631e+00 4.38566438e+00 4.63716956e+00
 3.99519918e+00 4.29614824e+00 3.33291796e+00 3.91227132e+00
 1.30814377e-10 1.69492318e-10 1.02050926e-10 1.27718909e-10
 1.21652381e-10 1.56931523e-10 1.40172811e-10 1.71187399e-10
 1.11358286e-10 1.49644172e-10 1.37112966e-10 1.72008165e-10
 3.98077325e+00 4.76313345e+00 3.46424798e+00 3.91409530e+00
 3.81204481e+00 4.496932

[1.31628870e+00 1.24563831e+00 9.50462925e-01 9.80416758e-01
 8.55464351e-01 8.26481244e-01 1.17964228e+00 1.14369632e+00
 9.84782317e-01 9.50512025e-01 8.15740922e-01 7.87730422e-01
 6.57156654e+00 6.32874642e+00 5.23683231e+00 5.36055872e+00
 4.86481934e+00 4.81178497e+00 6.09203119e+00 5.97251438e+00
 5.38804211e+00 5.26118751e+00 4.75927395e+00 4.64425846e+00
 5.33773672e-01 6.18645612e-01 5.87721682e-01 6.08183184e-01
 3.70980593e-01 4.02616180e-01 5.87534288e-01 6.61352983e-01
 6.20235490e-01 6.34161044e-01 4.00063598e-01 4.25984623e-01
 4.75261431e+00 5.13736262e+00 4.86171734e+00 5.03318472e+00
 3.91118995e+00 4.17851486e+00 5.03317267e+00 5.37378456e+00
 5.04320851e+00 5.21231369e+00 4.07582147e+00 4.22222333e+00
 1.52397446e-10 1.61432388e-10 1.34386388e-10 1.47102051e-10
 1.39724760e-10 1.67746466e-10 1.58807192e-10 1.74037684e-10
 1.49904313e-10 1.60255671e-10 1.46419891e-10 1.59692383e-10
 4.48529172e+00 4.67717353e+00 4.13580852e+00 4.38107403e+00
 4.24753486e+00 4.836394

[6.10014342e-01 7.65998117e-01 5.95676225e-01 7.14219404e-01
 5.93714567e-01 7.21750732e-01 6.73182042e-01 7.78994260e-01
 7.72093155e-01 8.45420582e-01 6.89794451e-01 7.78372682e-01
 3.83047221e+00 4.61343123e+00 3.84641397e+00 4.38764107e+00
 3.75355251e+00 4.41728025e+00 4.11319041e+00 4.62834775e+00
 4.51736715e+00 4.87148129e+00 4.18727201e+00 4.61432596e+00
 8.11720649e-02 1.35010367e-01 1.20506543e-01 1.91905571e-01
 1.00749215e-01 1.61680012e-01 9.92380990e-02 1.77898158e-01
 1.47884894e-01 2.09870663e-01 8.45737449e-02 1.39310983e-01
 2.24009523e+00 2.80021261e+00 2.55642013e+00 3.08429964e+00
 2.34139897e+00 2.94757983e+00 2.43232262e+00 3.00260664e+00
 2.72382633e+00 3.21620826e+00 2.33764736e+00 2.79034966e+00
 2.17401339e-10 3.52800123e-10 2.51452227e-10 2.95812650e-10
 1.91312908e-10 2.96728949e-10 2.66904524e-10 3.41407216e-10
 2.42752966e-10 3.06113091e-10 2.09021911e-10 2.73404890e-10
 3.24093285e+00 4.28883399e+00 3.49067456e+00 3.82567879e+00
 3.04913123e+00 3.844816

[4.75418622e-01 4.86325253e-01 3.66560941e-01 3.59238077e-01
 2.69959707e-01 3.28214153e-01 4.73634651e-01 4.96551819e-01
 3.66946400e-01 4.58625066e-01 3.19002951e-01 4.13975978e-01
 3.40889531e+00 3.56258952e+00 2.95950661e+00 2.97105308e+00
 2.47461088e+00 2.80344020e+00 3.55126561e+00 3.72975705e+00
 2.99862980e+00 3.48879450e+00 2.73539798e+00 3.28096951e+00
 9.42610451e-02 1.14208539e-01 7.98641228e-02 9.50274579e-02
 7.15633447e-02 9.19885175e-02 1.00699100e-01 1.38236396e-01
 7.76761155e-02 1.17910015e-01 7.16854770e-02 9.30555850e-02
 2.40272895e+00 2.66337058e+00 2.24584634e+00 2.39026174e+00
 2.01202852e+00 2.29486693e+00 2.60896692e+00 2.87807769e+00
 2.24373747e+00 2.72069587e+00 2.15622530e+00 2.55640947e+00
 1.06123853e-10 1.16784304e-10 1.61301021e-10 1.08887800e-10
 8.15117223e-11 1.02598834e-10 1.32412290e-10 1.32983694e-10
 1.41594647e-10 1.30827063e-10 1.01662429e-10 1.30567683e-10
 2.98965570e+00 3.12808180e+00 3.38978381e+00 3.02766359e+00
 2.69322625e+00 2.947050

[6.66194482e-01 7.03329493e-01 5.22352655e-01 5.65891120e-01
 4.72339699e-01 5.22957736e-01 6.38439935e-01 6.89281175e-01
 5.14372260e-01 5.55938146e-01 4.05089088e-01 4.57924057e-01
 4.17666115e+00 4.37521551e+00 3.62324577e+00 3.85587426e+00
 3.47673401e+00 3.70842954e+00 4.08380536e+00 4.37946794e+00
 3.58854383e+00 3.81899744e+00 3.22538741e+00 3.48869625e+00
 4.01016999e-01 4.48661999e-01 3.19148483e-01 3.88065410e-01
 2.77963466e-01 3.37089160e-01 4.52756501e-01 5.14555785e-01
 3.78900128e-01 4.57412022e-01 3.11745995e-01 3.57974580e-01
 4.06532033e+00 4.42654178e+00 3.61466126e+00 4.06032111e+00
 3.49561067e+00 3.87630323e+00 4.34400756e+00 4.73210200e+00
 3.89805901e+00 4.43715076e+00 3.67145185e+00 4.00564600e+00
 1.11792996e-10 1.25508331e-10 1.06464892e-10 1.06328887e-10
 1.15219805e-10 1.35283722e-10 1.07097249e-10 1.34825344e-10
 9.72454815e-11 1.16445374e-10 1.10228466e-10 1.30155101e-10
 4.01983172e+00 4.28683853e+00 3.76239676e+00 3.87513112e+00
 4.09315211e+00 4.537072

[9.14575610e-01 9.12751871e-01 8.50956582e-01 8.50032501e-01
 7.62189448e-01 7.71813608e-01 8.16067531e-01 8.41256586e-01
 8.44543915e-01 8.97982552e-01 7.41098280e-01 8.00154304e-01
 5.16622079e+00 5.17530067e+00 4.92233483e+00 4.94076255e+00
 4.58972654e+00 4.65811784e+00 4.82791199e+00 4.99278101e+00
 4.85373299e+00 5.07288204e+00 4.51481956e+00 4.76376632e+00
 1.83687631e-01 2.37017221e-01 2.62929369e-01 3.03173532e-01
 1.59065489e-01 1.88057710e-01 2.48058961e-01 3.13677950e-01
 3.84753991e-01 4.07555150e-01 1.94551766e-01 2.42589311e-01
 3.13254171e+00 3.39537204e+00 3.52935620e+00 3.74017818e+00
 2.99703497e+00 3.17683264e+00 3.39834087e+00 3.82099520e+00
 4.04701326e+00 4.26380973e+00 3.13971359e+00 3.44886966e+00
 3.31075834e-10 4.02921519e-10 3.24497391e-10 3.57277039e-10
 3.52733691e-10 4.07519936e-10 3.17039115e-10 3.97853354e-10
 2.69178813e-10 3.64471381e-10 3.65195509e-10 3.85069430e-10
 3.97467881e+00 4.51870996e+00 3.92953171e+00 4.12924094e+00
 4.13799419e+00 4.537851

[7.30681043e-01 7.73238426e-01 6.88116322e-01 7.11914702e-01
 5.71819613e-01 6.16600721e-01 8.30216709e-01 8.43075610e-01
 7.03979275e-01 8.02825063e-01 5.86711249e-01 5.33956527e-01
 4.46707411e+00 4.66854561e+00 4.29153809e+00 4.42815230e+00
 3.87565775e+00 4.07592726e+00 4.83388680e+00 4.90027537e+00
 4.28371525e+00 4.71467379e+00 3.94578285e+00 3.78697575e+00
 1.78900996e-01 2.31029674e-01 2.54624786e-01 2.72025581e-01
 1.69200631e-01 1.90881967e-01 1.10170165e-01 1.31040814e-01
 1.61681072e-01 1.79308456e-01 8.56216483e-02 1.05506493e-01
 3.06407794e+00 3.37776638e+00 3.46338365e+00 3.60218518e+00
 2.97709889e+00 3.16057040e+00 2.65027379e+00 2.81637942e+00
 2.80681792e+00 3.02482952e+00 2.52914752e+00 2.67132080e+00
 1.79836728e-10 2.28110529e-10 1.58992734e-10 2.09874263e-10
 1.69008388e-10 2.20955982e-10 1.90872677e-10 2.21628164e-10
 1.46295135e-10 1.59507586e-10 1.98118651e-10 2.00353487e-10
 4.16657683e+00 4.94230345e+00 3.84120757e+00 4.61479837e+00
 4.02652596e+00 4.839976

[5.42141708e-01 6.98140211e-01 3.73515979e-01 5.66298421e-01
 4.20283339e-01 5.41528835e-01 5.70608997e-01 6.54498056e-01
 4.58691884e-01 5.28667300e-01 1.37298900e-01 3.66201328e-02
 3.58775295e+00 4.26793927e+00 2.88958784e+00 3.77289521e+00
 3.11554663e+00 3.74496758e+00 3.73677289e+00 4.10529777e+00
 3.18441507e+00 3.52867648e+00 1.63858087e+00 1.16521739e+00
 1.54935110e-01 2.11285939e-01 1.71875936e-01 2.31601619e-01
 9.35069362e-02 1.66329529e-01 1.03323329e-01 1.39153446e-01
 1.29241403e-01 1.94546632e-01 2.39968895e-02 3.00177053e-03
 2.64950924e+00 3.25103035e+00 2.62831159e+00 3.22910442e+00
 2.28382779e+00 2.96066061e+00 2.43497089e+00 2.81323945e+00
 2.39007216e+00 2.87812336e+00 1.28821281e+00 1.05543478e+00
 1.68162480e-10 2.78723619e-10 1.57209061e-10 2.22296528e-10
 1.80123456e-10 2.65039043e-10 2.29935783e-10 3.04108247e-10
 1.63886430e-10 1.82851922e-10 6.50232128e-11 4.62651817e-11
 3.06790349e+00 4.03594526e+00 2.98028046e+00 3.52676398e+00
 3.18226029e+00 3.916679

/home/peppermint/.virtualenvs/cv/lib/python3.6/site-packages/ipykernel_launcher.py:441: RuntimeWarning: Mean of empty slice


[7.58126833e-01 7.98792527e-01 5.16822643e-01 6.82981959e-01
 5.86605302e-01 6.31137240e-01 6.31833859e-01 6.95582106e-01
 4.77932527e-01 5.66359943e-01 2.87601525e-01            nan
 4.50658567e+00 4.74175188e+00 3.46646161e+00 4.18893395e+00
 3.81336081e+00 4.10715771e+00 3.97965238e+00 4.26907265e+00
 3.21910061e+00 3.64731153e+00 2.45634921e+00            nan
 1.53224098e-01 1.96917864e-01 1.81450706e-01 2.34206911e-01
 7.33995565e-02 1.22950735e-01 6.92094887e-02 9.58440602e-02
 1.09262627e-01 1.39842858e-01 9.07436627e-02            nan
 2.82020852e+00 3.17359359e+00 2.73508060e+00 3.21698672e+00
 2.27669008e+00 2.72489452e+00 2.27001369e+00 2.53879337e+00
 2.20224147e+00 2.52760123e+00 1.76498016e+00            nan
 2.42901781e-10 3.19354048e-10 1.76937512e-10 2.25390687e-10
 2.34478723e-10 3.06325270e-10 2.51669139e-10 3.14838334e-10
 1.46490753e-10 1.65204927e-10 1.40935138e-10            nan
 3.60732247e+00 4.27447691e+00 3.09389832e+00 3.49135450e+00
 3.56607723e+00 4.180399

[1.17512729e+00 1.16226534e+00 1.00764879e+00 1.01102593e+00
 7.91364212e-01 8.32375842e-01 1.18289895e+00 1.15362894e+00
 1.06775611e+00 1.09856029e+00 9.91972898e-01 9.83198775e-01
 6.05064981e+00 6.01935304e+00 5.41901525e+00 5.44835141e+00
 4.63323060e+00 4.83198469e+00 6.08551493e+00 6.01475588e+00
 5.63805377e+00 5.77615669e+00 5.38784864e+00 5.38781259e+00
 1.80629863e-01 2.44311767e-01 2.06369906e-01 2.52009238e-01
 9.80200595e-02 1.11389468e-01 2.23776608e-01 3.37920324e-01
 2.42060666e-01 3.20541860e-01 1.55640861e-01 2.35067940e-01
 3.03420281e+00 3.40439118e+00 3.13688683e+00 3.42746274e+00
 2.54510188e+00 2.68290368e+00 3.26402452e+00 3.90227079e+00
 3.31617910e+00 3.79490005e+00 2.88677717e+00 3.40368767e+00
 2.74716136e-10 3.20685583e-10 2.26876018e-10 3.04389191e-10
 2.66188384e-10 3.41992305e-10 2.76621195e-10 2.91776085e-10
 2.51993264e-10 2.92604715e-10 2.65072398e-10 3.39366530e-10
 4.06291389e+00 4.48169850e+00 3.62736318e+00 4.34536505e+00
 4.02869919e+00 4.778105

[7.97323133e-01 8.22579312e-01 6.00818654e-01 5.99855503e-01
 5.28846610e-01 5.76806143e-01 7.47820952e-01 7.90830087e-01
 6.07239323e-01 6.84722682e-01 4.24007385e-01 4.93768940e-01
 4.63888766e+00 4.78903727e+00 3.78595955e+00 3.92142752e+00
 3.59705620e+00 3.86232171e+00 4.47960405e+00 4.71600847e+00
 3.89158300e+00 4.29939030e+00 3.25409593e+00 3.57367064e+00
 1.85332020e-01 2.54466997e-01 2.35025801e-01 2.68620573e-01
 1.75031044e-01 1.86623005e-01 1.80332568e-01 2.19498569e-01
 2.11957494e-01 2.41407689e-01 1.30040589e-01 1.46806292e-01
 2.97354636e+00 3.44224928e+00 3.00070978e+00 3.38963298e+00
 2.75897345e+00 2.99545606e+00 2.98298764e+00 3.29210412e+00
 3.03982317e+00 3.38978931e+00 2.62993812e+00 2.83268797e+00
 2.02548240e-10 2.56093257e-10 1.55872921e-10 1.97285159e-10
 1.89293911e-10 2.34302124e-10 2.14255147e-10 2.74433134e-10
 1.81750015e-10 2.31268726e-10 1.97912912e-10 2.37767698e-10
 3.71205662e+00 4.27235399e+00 3.22839647e+00 3.65175223e+00
 3.57664106e+00 4.073034

[1.64025204e+00 1.70322118e+00 1.47494232e+00 1.54555777e+00
 1.26592627e+00 1.31589093e+00 1.65731131e+00 1.74691145e+00
 1.64897294e+00 1.68330045e+00 1.48745990e+00 1.51336728e+00
 7.62958171e+00 7.92476229e+00 7.08447989e+00 7.38032880e+00
 6.33754624e+00 6.54710016e+00 7.64613624e+00 7.99304354e+00
 7.60102130e+00 7.80604129e+00 7.13897786e+00 7.23620576e+00
 1.76732241e-01 1.98255181e-01 2.97670203e-01 2.81483812e-01
 1.77209661e-01 1.61158553e-01 2.38803594e-01 2.59478374e-01
 3.35164261e-01 3.56625714e-01 1.74682470e-01 1.91113911e-01
 2.99892549e+00 3.17206622e+00 3.60498421e+00 3.60712772e+00
 2.96816687e+00 2.98948260e+00 3.30969798e+00 3.47057140e+00
 3.76275482e+00 3.92575479e+00 2.97278974e+00 3.13780071e+00
 1.48761800e-10 1.85334336e-10 1.36893873e-10 1.69613808e-10
 1.31973996e-10 1.90905753e-10 1.55180395e-10 1.92525046e-10
 1.48776849e-10 1.73579661e-10 1.61199919e-10 1.75142215e-10
 4.09253781e+00 4.78261133e+00 3.91745639e+00 4.48201788e+00
 3.81597107e+00 4.926699

[7.74501462e-01 8.82024266e-01 8.00785374e-01 8.74950537e-01
 5.73238608e-01 6.39293577e-01 9.63441041e-01 1.02285998e+00
 8.71492001e-01 9.27900975e-01 7.23503045e-01 7.18465315e-01
 5.01338716e+00 5.57506189e+00 5.15136363e+00 5.54291657e+00
 4.07958594e+00 4.44719095e+00 5.80334267e+00 6.17976622e+00
 5.31048103e+00 5.74406052e+00 4.58732690e+00 4.77995007e+00
 1.19189436e-01 1.09217837e-01 2.19416769e-01 1.83385900e-01
 2.19624471e-01 1.74383596e-01 1.50245717e-01 1.60278733e-01
 3.48501066e-01 2.91861325e-01 3.30109534e-01 2.22103513e-01
 2.70186067e+00 2.81675375e+00 3.29509908e+00 3.24511499e+00
 3.10510136e+00 3.04870175e+00 2.88173250e+00 3.04966868e+00
 3.69535592e+00 3.75202659e+00 3.28195934e+00 3.27987989e+00
 8.58615942e-11 1.10814384e-10 8.70107595e-11 1.07845666e-10
 8.16795228e-11 9.87444459e-11 9.18527906e-11 1.09841031e-10
 7.98477172e-11 9.48769270e-11 7.78497374e-11 9.73136914e-11
 3.57665508e+00 4.22625697e+00 3.60013402e+00 4.15043400e+00
 3.47818559e+00 3.934261

[1.17234116e+00 1.07970682e+00 8.78699658e-01 8.60681250e-01
 6.53108627e-01 7.05613067e-01 9.62384566e-01 9.45681988e-01
 7.87616542e-01 8.35817007e-01 6.86218825e-01 7.08340195e-01
 6.06301368e+00 5.73664809e+00 4.94818377e+00 4.95368606e+00
 4.05567821e+00 4.33264890e+00 5.30081346e+00 5.25375557e+00
 4.64422776e+00 4.86711975e+00 4.28990437e+00 4.37482705e+00
 3.05527219e-01 3.95875516e-01 3.66102647e-01 4.13309863e-01
 3.06312100e-01 3.19117328e-01 3.31558838e-01 3.66443697e-01
 3.80407006e-01 3.81830588e-01 2.70899394e-01 2.69385043e-01
 3.73656660e+00 4.20910953e+00 3.92710214e+00 4.28016884e+00
 3.37623644e+00 3.73237361e+00 3.83989896e+00 4.05944974e+00
 4.06127695e+00 4.14012789e+00 3.51622513e+00 3.57514621e+00
 1.45246671e-10 1.58364906e-10 1.21729047e-10 1.56732617e-10
 1.02840333e-10 1.41145290e-10 1.34622369e-10 1.62343379e-10
 1.26789866e-10 1.59486041e-10 1.34394301e-10 1.59212731e-10
 4.59447357e+00 4.89059625e+00 4.08642039e+00 4.86541594e+00
 3.71738309e+00 4.561417

[6.96318257e-01 7.08393891e-01 5.45613209e-01 6.17538776e-01
 5.37059037e-01 5.65976784e-01 7.69334153e-01 7.76653020e-01
 6.61054652e-01 6.71765136e-01 5.27513135e-01 5.45751325e-01
 4.32517454e+00 4.37461161e+00 3.80249152e+00 4.06438692e+00
 3.82642517e+00 3.94557906e+00 4.63272456e+00 4.66743607e+00
 4.22912085e+00 4.28132590e+00 3.76949967e+00 3.85585321e+00
 4.58881872e-01 4.77592552e-01 4.75839017e-01 5.05589419e-01
 2.48093910e-01 2.76621348e-01 4.36152583e-01 4.35074480e-01
 4.43225990e-01 4.37318253e-01 2.31021985e-01 2.71386499e-01
 4.50497128e+00 4.61045725e+00 4.54513424e+00 4.71658451e+00
 3.46007451e+00 3.61701623e+00 4.40682190e+00 4.42632088e+00
 4.43512566e+00 4.41083797e+00 3.37561781e+00 3.59285585e+00
 2.09506289e-10 2.21103178e-10 1.92663842e-10 2.14380235e-10
 2.10815670e-10 2.36345843e-10 2.07308308e-10 2.30215250e-10
 2.02154449e-10 2.29337257e-10 2.15514639e-10 2.37400621e-10
 4.78577160e+00 4.99235022e+00 4.54228670e+00 4.90413231e+00
 4.85169274e+00 5.322418